### ISSUE TITLE
Video: player should be responsive

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#101]
### Steps to Reproduce

1. Open a page with the video player, for example https://ocwnext-rc.odl.mit.edu/courses/18-s096-topics-in-mathematics-with-applications-in-finance-fall-2013/sections/video-lectures/lecture-1-introduction-financial-terms-and-concepts/
2. View the page at mobile width.
3. View the page at tableet width. 
4. Close the course info drawer. 

### Expected Behavior

The video player should be responsive and resize to the available screen width. 

### Actual Behavior

- The player overlaps content at tablet width
- The player gets cut off at mobile width
- The player doesn't use all the available space when the course info drawer is closed (less critical) 

### Screenshot or Screencast

From Firefox, using the responsive developer tool, mobile breakpoint:

![Screen Shot 2021-06-11 at 11 35 55](https://user-images.githubusercontent.com/430126/121554352-178e6f80-c9e0-11eb-8ccc-5130e11c7c61.png)

From firefox, resizing the browser width manually:

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/430126/121554619-4dcbef00-c9e0-11eb-9065-38b227c43388.png">

From firefox, desktop browser with course info drawer closed:

<img width="1763" alt="image" src="https://user-images.githubusercontent.com/430126/121554755-6a682700-c9e0-11eb-90f3-d3a2a266168b.png">

**Comment by noisecapella** [comment]
I'm not seeing an issue when I view that link, but I'm also seeing an embedded youtube widget and not video.js. Maybe this was fixed when #35 was reverted

**Comment by pdpinch** [comment]
Yeah, this is only relevant to the video.js player.
