### ISSUE TITLE
Home page: carousels should have 12 items

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#1025]
The new courses carousel ends abruptly at 10 items, which makes it look broken at desktop widths: 

![image](https://user-images.githubusercontent.com/430126/210634877-7057add1-d833-4fe0-a26b-2a8360830468.png)

and iPad horizontal: 

![image](https://user-images.githubusercontent.com/430126/210635018-b97436af-ffb3-4e7b-8b81-12112a9482db.png)

#### Acceptance Criteria:

- [ ] Change it to 12 items, which divides nicely into 2, 3 and 4 items per page.

**Comment by ChristopherChudzicki** [comment]
@pdpinch Changing the New Courses carousel to 12 items should be straightforward and will improve the aesthetics.

The Featured Courses carousel, however, is populated manually by a list created in Studio. So it could have any number of items, up to the OCW team. Currently it has 13, so the last page doesn't look great.

<img width="300" alt="Screenshot 2023-01-09 at 10 02 13 AM" src="https://user-images.githubusercontent.com/9010790/211339485-9da72081-e031-4324-b442-efbc51f0df27.png">

We could:
- advise OCW team to make 12 featured courses
- use a different carousel library
