### ISSUE TITLE
Course info expander isn't collapsing

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-hugo-themes#104]
### Steps to Reproduce

Go to https://ocwnext.odl.mit.edu/courses/18-01-single-variable-calculus-fall-2006/ and click the "Course Info" header. You should be able to toggle it open and closed but it will only open.

I don't see any console warnings or errors, but it's very likely the problem is in `course_expander.js`

In this screenshot, the caret should be pointing to the right but it's pointing down instead.
![Screenshot from 2021-01-27 16-41-27](https://user-images.githubusercontent.com/863262/106057857-88cb2700-60be-11eb-99d7-6c4190fcb087.png)

**Comment by pdpinch** [comment]
@noisecapella is this still an issue?
