### ISSUE TITLE
Use correct logo on homepage

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-hugo-themes#1070]
The homepage and the course pages are using different logos. The homepage is using the old raster logo:

<img width="300" alt="Screenshot 2023-02-02 at 12 44 19 PM" src="https://user-images.githubusercontent.com/9010790/216402183-a8e8ce8a-cb0b-4355-bd18-7faf59af90b5.png"> <img width="300" alt="Screenshot 2023-02-02 at 12 44 12 PM" src="https://user-images.githubusercontent.com/9010790/216402179-89f97322-07a0-4a6d-82cd-e99bd61214f6.png">

Additionally, we should address this comment in [header.html](https://github.com/mitodl/ocw-hugo-themes/blob/main/base-theme/layouts/partials/header.html#L21-L22):
```html
      <!-- TODO: Currently rendering different logos for different course themes via CSS
      This should be undone and ocw_logo_white_v2 should be used when we completely move to new course theme -->
```

### Acceptance Criteria:
- [ ] header at ocw.mit.edu should use same logo (the v2 svg version) as that used in course-v2 theme.
- [ ] The TODO note above should be addressed, and any related TODOs

**Comment by fakhar-ud-din** [comment]
Hey everyone,

This issue has been addressed [here](https://github.com/mitodl/ocw-hugo-themes/pull/1074) by @MAbdurrehman12. Once [this PR](https://github.com/mitodl/ocw-hugo-themes/pull/1074) get merged, we can safely close this ticket too.

Thank You
