### ISSUE TITLE
Studio Heading 1 and Heading 2 both render as `<h3>` 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#1097]
### Steps to Reproduce

1. Create a page in Studio
2. Add some text with "Heading 1" style
3. Add some text with "Heading 2" style 
4. Publish the page

### Expected Behavior

- "Heading 1" and "Heading 2" should have different styling to distinguish them

### Actual Behavior

- "Heading  1" and "Heading 2" look the same
- they both renders with `<h3>` HTML tags 

### Screenshot or Screencast

compare https://ocw-studio-rc.odl.mit.edu/sites/peters-test-site-for-unpbulishing/type/page/edit/7e4f5b8c-9592-495f-b2c4-8423c788ec41/ 

<img width="169" alt="image" src="https://user-images.githubusercontent.com/430126/221989020-555416f1-0b0d-4306-867d-05b6589c487f.png">

and  https://draft-qa.ocw.mit.edu/courses/test101-peters-test-site-spring-2023/pages/a-page-full-of-headers/

<img width="90" alt="image" src="https://user-images.githubusercontent.com/430126/221989113-fb62a9cc-43c5-45e0-a443-c67ca20558b0.png">

**Comment by pdpinch** [comment]
While you are working on this, note that the  "Heading 3" text is styled red when it should be black. Compare to the style guide: https://projects.invisionapp.com/d/#/console/21537330/468374061/comments

**Comment by ibrahimjaved12** [comment]
We are using goldmark (markdown handler) to handle markdown files.
Inside .md files, the different headings are differentiated as:
Heading 1 is represented as `## This is a heading one`
Heading 2 is represented as `### This is a heading one`
Heading 3 is represented as `#### This is a heading one`
By default goldmark is configured to have X number of `#` for `<hX>` heading and it appears to be true for ocw-www theme, I tested for `##`, `###`, `####`, and they are h2, h3, and h4 respectively.
<img width="390" alt="image" src="https://user-images.githubusercontent.com/109785089/224300933-838d8633-d8d3-4563-9433-07ba972a97d7.png">
However for ocw-course, it's showing the behaviour mentioned in this issue.

I'll perform further R&D on this to see why are these rendered differently for course and www, like from which point in code is this behaviour coming from; possibly from some template. The PR I upped does not resolve this yet.

**Comment by ibrahimjaved12** [comment]
@pdpinch Need your clarification on something:
We have this course lists page:
https://ocw.mit.edu/course-lists/open-learning-library/
It currently has red styled h1 heading which has applied styling of h2 with caps (MIT OPEN LEARNING LIBRARY). Plus, currently this same heading size is also applied to mobile screen size. Other than that, there are more headings on this page.
But [OCW Style Guide](https://projects.invisionapp.com/d/#/console/21537330/468374061/comments) does not mention anything for this. How should this be handled.

Also: I noticed a few inconsistencies of our current themes in relation to the style guide (such that h4 and h5 are not actually h4 and h5, but they are div texts with applied styling to achieve the behaviour). But I believe they are out of scope for this ticket. I'll R&D what other inconsistencies are there and open an issue for that after this.
