### ISSUE TITLE
Use proper heading tags instead of <div> 

### ISSUE THREAD

**Issue by ibrahimjaved12** [mitodl/ocw-hugo-themes#1105]
### Steps to Reproduce

Follow [this](https://projects.invisionapp.com/d/#/console/21537330/468374061/comments) style guide
1. Open any course, eg. https://ocw.mit.edu/courses/5-35-introduction-to-experimental-chemistry-fall-2012/pages/syllabus/
2. The title "Introduction To Experimental Chemistry" need to be an `h1` tag. It is currently `a` tag with applied styling of font-weight, font-size, etc to make it look like `h1`
3. Inspect the panel on the right. The `COURSE INFO` title should be `h4` but it is a `div`.
4. Similarly right underneath `COURSE INFO`, notice the underneath headings, eg. `INSTRUCTORS`. This should be `h5` but it is also a `div`.

### Expected Behavior

The headings should use proper `h` tags instead of `div`. 
This will be better for accessibility and also semantically the right thing to do.

### Actual Behavior
Currently they're using `div` tags with styling to appear as headings.

### Other headings
I wanted to bring to attention a couple more things to confirm that they're correct or not.
(Refer to screenshots)

1. Home page issues moved to https://github.com/mitodl/ocw-hugo-themes/issues/1136
5. In courses theme, we have another subheading here, and I'm not too sure about this one. Scroll [this](https://ocw.mit.edu/courses/5-35-introduction-to-experimental-chemistry-fall-2012/pages/syllabus/) link down to "Module 1 Fundamentals of Spectroscopy". This currently has `strong` tag. Not sure if this is correct behaviour or not. Maybe this was supposed to be `h4`. 
7. Search page issues moved to https://github.com/mitodl/ocw-hugo-themes/issues/382

### Related Issues

- #1097 
- https://github.com/mitodl/ocw-hugo-themes/issues/1136

### Screenshot or Screencast

<img width="1523" alt="image" src="https://user-images.githubusercontent.com/109785089/225251218-e857db96-cb08-4f2a-863b-fbba07283b49.png">
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/109785089/225251543-d81a4b09-f5fc-43b3-bc46-19bbf3892925.png">
<img width="337" alt="image" src="https://user-images.githubusercontent.com/109785089/225256947-627e6ee8-dd21-4ca9-9e8f-36411c340032.png">
<img width="803" alt="image" src="https://user-images.githubusercontent.com/109785089/225257055-bde0164b-f604-4e0d-84a3-c7c9c1191eec.png">
<img width="809" alt="image" src="https://user-images.githubusercontent.com/109785089/225257386-30ba214c-7d4b-484e-bc29-9e930a3a22bf.png">

![image](https://user-images.githubusercontent.com/109785089/225274073-38fb2a67-393e-402b-ba6c-cd2da87a84ec.png)
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/109785089/225274238-204b0ff5-8c05-4bec-bba7-57d73fa02f39.png">

**Comment by ChristopherChudzicki** [comment]
When this gets tackled, it would be a good opportunity to add associated playwright tests for some of this functionality. E.g., `page.getByRole("heading", { name: "Instructors" })`. *We have a similar test for course info on the course homepage, but not on the course info panel shown on other pages.*
