### ISSUE TITLE
add theme for offline root website

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-hugo-themes#1111]
As part of https://github.com/mitodl/hq/issues/785, we need to provide an offline version of the `www` theme, aka the root website. This theme should:

 - [x] Using Hugo's [pagination](https://gohugo.io/templates/pagination/), create a paginated list of courses based on content of type "website" produced by `ocw-studio` added in [this PR](https://github.com/mitodl/ocw-studio/pull/1705)
 - [x] Each course card should assume that an offline course site exists at the `url_path` front matter property and render a link to it
 - [x] Render an `index.html` page with pagination controls that displays said pages

**Comment by gumaerc** [comment]
@pdpinch @Ferdi I made more progress on this today, styling the course cards like the search result cards:

![image](https://user-images.githubusercontent.com/12089658/226482112-e6398dca-96ed-4bc2-aa66-fb963a179545.png)

Some things to think about:

 - In the content I'm using to generate this (generated by https://github.com/mitodl/ocw-studio/pull/1705) instructors are only referenced by UUID, the same way they are in the course metadata. Therefore, we need to fetch them during the build like we do during course builds. This isn't the end of the world, as the build still completes in about 4 minutes, but it does make it susceptible to the same kind of build failures as the course sites if an instructor can't be found / hasn't been deployed yet.
 - In a similar fashion, the course image is referenced by UUID and normally only fetched by course being rendered. I'm currently handling this by fetching the `data.json` from the deployed course site and using the `image_src` property to generate the `img` tag. This is the same data that `open-discussions` fetches to build the search index.

I'm not sure if either of these are worth addressing, but instead of doing this I was thinking that instead we might want to modify the code I wrote in `ocw-studio` to instead write in static instructor names and image paths. Because of the way it's set up as a prepublish action, if the instructors or images are updated then that info will also be updated in `ocw-www` as part of the publish. It would simplify this work and make it less prone to failure.

**Comment by pdpinch** [comment]
Let's base this off of the ["compact" design](https://ocw.mit.edu/search/?u=compact) instead. It doesn't have instructors so we can sidestep this concern.

**Comment by gumaerc** [comment]
@pdpinch @Ferdi Okay, I reworked this to use the compact design. fixed up the pagination controls to work offline and sorted the courses by course number. Right now I have the `paginate` setting in the config set to 20, so 20 items per page.

![image](https://user-images.githubusercontent.com/12089658/226759345-e166a257-486f-4d2d-855d-1791f1c9ae55.png)

My only remaining question is what we want to do about the header. It makes sense for the logo to go back to page 1, but what about the rest of the links? Our strategy with the header in the offline course sites is to link those to the live site, so if you click give now, contact, etc. it will go there. I don't really think this makes sense for mirror drives, does it? Should we hide the links, or display something else?

**Comment by pdpinch** [comment]
> My only remaining question is what we want to do about the header.

You're already changing 34 files in your PR. Can we pull out the header into a separate issue, to address later?

**Comment by Ferdi** [comment]
Can we put the pagination buttons  at the bottom ?
