### ISSUE TITLE
Overwriting Input File Errors in tsconfig.json

### ISSUE THREAD

**Issue by ibrahimjaved12** [mitodl/ocw-hugo-themes#1114]
### Steps to Reproduce

Run: `npx tsc --build `
You'll see a list of all of those errors.

### Expected Behavior

There shouldn't be errors.

### Actual Behavior

There are errors reported by `tsc --build` (and also by VS Code)

### Screenshot or Screencast

These are all 11 errors:

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/109785089/226828178-ecb4049b-4089-40ca-8c4e-db4d4d08e7ed.png">
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/109785089/226827906-0f9576e8-fb3f-4731-aedd-0e0012083c5a.png">

I noticed these errors when I was working on videojs stuff (https://github.com/mitodl/ocw-hugo-themes/pull/1089) That's when they were reported by VS Code.
This is coming from the VS Code Typescript Extension.
If we don't have an output directory (`outDir`) in `compilerOptions` inside `tsconfig.json`, the compiled JavaScript files overwrites the input files. And that's where these errors are coming from.

**Comment by pdpinch** [comment]
Does this block work, or is it tech debt?

**Comment by ibrahimjaved12** [comment]
> Does this block work, or is it tech debt?

The block does work, the errors are just reported by the compiler that have no impact on the functionalities. However, it's a simple quick 2-liner fix. 
Because they're 11 errors that are reported by VS Code, so we shouldn't have them ideally and other genuine errors might get skipped because of that. So I'll make a PR for this.
