### ISSUE TITLE
Broken Links in Related Resources

### ISSUE THREAD

**Issue by pt2302** [mitodl/ocw-hugo-themes#1116]
### Description

In certain legacy courses, there are related resources linked from the video pages. The links are embedded in the videos' metadata and currently written as raw links. Links to other resources, rather than absolute URLs, are not working. For example, the link `https://ocw.mit.edu/courses/res-18-005-highlights-of-calculus-spring-2010/resources/big-picture-derivatives/resources/mitres18_05s10_big_picture_derivatives/` should actually be `https://ocw.mit.edu/courses/resources/mitres18_05s10_big_picture_derivatives/` (i.e., the URL is relative to the referring resource page but shouldn't be).

There are three components to this issue:

- [ ] Update the video partial (https://github.com/mitodl/ocw-hugo-themes/blob/main/base-theme/layouts/partials/video.html) to handle resource link shortcodes.
- [ ] Add a Playwright test to verify that related resource links are handled correctly, both for absolute URLs and resource link shortcodes. 
- [ ] Fix the broken links in the database by updating the relevant metadata with `resource_link` shortcodes to the relevant UUIDs and republishing the affected courses (https://github.com/mitodl/ocw-studio/issues/1740).

**Comment by pdpinch** [comment]
This plan makes sense to me, but we should prioritize a quick fix https://github.com/mitodl/hq/issues/1091 before addressing the widespread issue.
