### ISSUE TITLE
Consider loading fewer font icons

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-hugo-themes#1134]
OCW Loads all the icons in two variants of Material Icon fonts:

```
https://ocw.mit.edu/static_shared/fonts/MaterialIcons-Regular.woff2                 82kb
https://ocw.mit.edu/static_shared/fonts/MaterialIconsRound-Regular.woff2            171kb
```

Some notes:
- We load **all** the icons for both "regular" and "round", despite using relatively few of the icons. *E.g., we use exactly one round icon; it's for the instructor-insights indicator on course info tab*. This is pretty wasteful. The size of the icons we actually use would be much, much smaller. 
-  This is about 30% of the assets downloaded for, say [5-111sc homepage](https://ocw.mit.edu/courses/5-111sc-principles-of-chemical-science-fall-2014/)
- Icon loading is here: https://github.com/mitodl/ocw-hugo-themes/blob/main/base-theme/layouts/partials/head.html#L22-L38  (note fallbacks... local -> woff2 -> woff -> truetype).

**User impact of font loading:** The user impact of icon font loading is that you briefly see a screen like the one below—("keyboard_arrow"—not great). On slower networks, the screen is visible longer. *Of course, the fonts are cached, so you only see it on first visit. Well, the caching isn't great yet. See #1212  *.

If we had much smaller icon fonts (e.g., by only including what we need) then either (a) the screen below would be only  visible very briefly, even on slower networks, or (b) if the fonts were small enough, we could load it synchronously with the rest of the CSS to avoid this screen altogether.
<img width="1186" alt="Screenshot 2023-04-25 at 3 03 21 PM" src="https://user-images.githubusercontent.com/9010790/234380869-c920d380-0744-4929-bef9-d2190aeb28d1.png">

**Comment by HussainTaj-arbisoft** [comment]
I thought about what we could do to minimize manual labor for this (now and in the future).

My initial goal was the make the entire thing automatic. We could use some webpack plugin to detect usages and subset the font. Unfortunately, our ways of using the icons vary and I did not find an existing solution that could help us. Creating our own usage detection algorithm might make this change a bit too complicated.

For now, I'm thinking of generating a list of icon names myself. And then subset the fonts during the webpack build phase. This has the benefit that any new icons will only require the engineer to add the name.

I'll first try out https://github.com/hk029/font-subset-loader. It hasn't been maintained for a while, so we need to verify if it's viable. If that doesn't work, I plan to try https://github.com/dzhuang/subset-iconfont or a similar subsetting tool.

As always, we have the option to manually create the subset font. I will consider this if things get too complicated.

**Comment by HussainTaj-arbisoft** [comment]
I tried a bunch of different font manipulation packages.

The way they define icons in code differs from what we currently have. This introduces a lot of change and effort which might not be worth it.

* https://github.com/dzhuang/subset-iconfont
   * Class names are used to define icons
* https://github.com/dalcib/material-icons-subset
   * Uses Material Design Icons provider. (Is older, unofficial, and has different icon names.)
* Various other direct font manipulation packages like https://www.npmjs.com/package/harfbuzzjs, https://www.npmjs.com/package/subset-font, https://www.npmjs.com/package/fontkit
   * These simply don't support the format we use. Their use would be through codepoints defined in CSS.

I'll try manual subsetting next. I don't plan on making it painfully manual (probably make a bash script), but I won't aim to make it part of the build phase.

**Comment by HussainTaj-arbisoft** [comment]
I've implemented a prototype of the manual approach in https://github.com/mitodl/ocw-hugo-themes/pull/1257.

@ChristopherChudzicki I would love to hear your feedback on the approach. The PR isn't ready yet, I just want to make sure I'm heading in the right direction before I complete it.
