### ISSUE TITLE
dynamically loaded css, js from bundle splitting doesn't work in offline site (video player, image galleries)

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-hugo-themes#1143]
### Steps to Reproduce

Build a site locally that has an image gallery, like https://github.mit.edu/ocw-content-rc/5.36-spring-2009 using the `course-offline` theme and view the HTML directly on your computer using the `file://` protocol by double clicking on the HTML file.

### Expected Behavior

The image gallery displays properly

### Actual Behavior

The page renders, but the image gallery is not displayed and an error about missing CSS is logged in the console

### Stacktrace

```
GET file:///static_shared/css/948.b8d41.css net::ERR_FILE_NOT_FOUND
(anonymous) @ css loading:25
(anonymous) @ css loading:47
r @ css loading:43
a.f.miniCss @ css loading:59
(anonymous) @ ensure chunk:6
a.e @ ensure chunk:5
window.initNanogallery2 @ course-v2.ts:35
window.onload @ index.html:798
load (async)
(anonymous) @ index.html:796
```

### Background Context

I believe this has to do with the Webpack bundle splitting functionality we added recently. The CSS link tag is being added dynamically at runtime with JS and the URL being used is a relative URL of type path-absolute, meaning it starts with a backslash. When running a site completely offline without a web server, the browser treats this as the root of your filesystem and the file is not found. The course-offline theme uses the relativeUrls: true Hugo setting to post-process href, src and other tags containing links, making them relative to the site root. This does not work, however, if the links are written in dynamically at runtime. We will need to use a different approach for offline sites in this regard.

### Screenshot or Screencast

![image](https://github.com/mitodl/ocw-hugo-themes/assets/12089658/080ace92-e49d-42eb-ae7c-0b58788707a3)

**Comment by ChristopherChudzicki** [comment]
This is also an issue for the video player: currently we don't include videos in the offline site, we just use the youtube player like on offline. But our VideoJS integration doesn't work without the dynamically loaded JS.

### Proposal: Stop dynamic bundle splitting the offline site
The primary advantage of the dynamic bundle splitting is that users do make network requests for stuff they aren't using[^1]. That's a bit deal for the online site. 

But "avoid extra network requests" doesn't matter for the offline site. The user already has everything on their hard drive.

**So let's just stop dynamic bundle splitting for the offline site.**

From googling, I think the best way to do this is:
```
    new webpack.optimize.LimitChunkCountPlugin({
      maxChunks: 1, // max chunks per entrypoint
    })
```

**Downside:** Now we'd have a separate webpack build for the offline site.

[^1]: The other advantage is that they also **do not parse/run** the unncessary javascript/css. But that's generally a small consideration compared to the network request itself.
