### ISSUE TITLE
video: control playback rate

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#139]
As a user, I'd like to control the video playback rate on OCW, the same as I can on YouTube. 

#### Designs and Mockups

https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/461529499/preview?scrollOffset=576

Be sure to scroll to the right, to see the new video player, with the "settings" control with the "gear" icon. 

![image](https://user-images.githubusercontent.com/430126/164322694-16abfca5-1b05-4fc9-af3f-51dc81aa9cce.png)

#### Acceptance Criteria:

- [ ] If we can, we should offer the same rates as YouTube does: 

<img width="279" alt="image" src="https://user-images.githubusercontent.com/430126/126649345-4028a8c1-607b-4f3d-abbe-3372b53b318a.png">

#### Related issues

- #140 
- #658

**Comment by MAbdurrehman12** [comment]
Playback rate button is enabled and works fine on adding `"playbackRates": [0.5, 0.75, 1, 1.25, 1.5, 1.75, 2],` in `data-setup` in `video` tag but the UI is not good as stated by @annagav in the above comment so I tried various plugins to get the desired result/UI for the `playback rate` button but they don't seem to work/integrate well leaving behind the thought of customizing the UI for it. 
I also had a discussion with @Wassaf-Shahzad, he was also having a tough time finding the right plugin for controlling video quality and he was also thinking of a customized solution, so maybe we can merge/handle this issue either in [control video quality issue](https://github.com/mitodl/ocw-hugo-themes/issues/140) or in [update player design issue](https://github.com/mitodl/ocw-hugo-themes/issues/658). 
There's some other approach too to handle this but it was also not working with the current implemented approach.

By the way, if we replace the `video.js` with youtube's iframe (Embedded Player), it has pretty much all the needed features with a nice UI as shown below (not sure if this approach is recommended as it has youtube's branding and maybe it does not offer that much customization which `video.js` offers though I'm sure youtube's iframe/embedded player also offers some customization):  

<img width="605" alt="image" src="https://user-images.githubusercontent.com/93309234/167410414-be33eb80-1627-48e2-934b-cdaecb3317e6.png">

<img width="304" alt="image" src="https://user-images.githubusercontent.com/93309234/167410435-c5db5f81-309e-4d72-900c-204d6f6c3f1f.png">

<img width="261" alt="image" src="https://user-images.githubusercontent.com/93309234/167410477-31bfc321-2f86-408b-b5be-7b02f4bca099.png">

<img width="269" alt="image" src="https://user-images.githubusercontent.com/93309234/167410513-e99cdb8a-de20-4838-bb54-1622b6ebb64c.png">

CC: @pdpinch @gumaerc

**Comment by pdpinch** [comment]
@Wassaf-Shahzad #709 will close this, right?

**Comment by Wassaf-Shahzad** [comment]
Closing this issue manually since #709 did not close it.
