### ISSUE TITLE
videojs failing initialization on pages with no video

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-hugo-themes#142]
### Steps to Reproduce

Visit a page without a video, such as a course home page

### Expected Behavior

The page loads without error

### Actual Behavior

The `videojs` library throws a `TypeError` error in the console

### Stacktrace

```
Uncaught TypeError: The element or ID supplied is not valid. (videojs)
    at Mo (course.dfbdd.js:2)
    at HTMLDocument.<anonymous> (course.dfbdd.js:2)
    at u (course.dfbdd.js:2)
    at c (course.dfbdd.js:2)
```

**Comment by annagav** [comment]
I could not find this error at first but now I found that it happens on the sections/video-lectures/ page where all lectures are listed.
