### ISSUE TITLE
horizontal scroll bar on topics in drawer

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#255]
### Steps to Reproduce

1. Visit my test course at https://ocw-draft-qa.global.ssl.fastly.net/courses/peters-test-2021-09-29-1/pages/asdf/
2. Using responsive mode, set the browser width to "Laptop with MDPI screen"

### Expected Behavior

right side drawer is responsive, but without scrollbars. 

### Actual Behavior

right side drawer displays a horizontal scrollbar

### Screenshot or Screencast

![image](https://user-images.githubusercontent.com/430126/141000007-c360e19b-a6e4-4380-b84d-b39afb29fa23.png)

**Comment by pdpinch** [comment]
I can't reproduce this the same way, but if I use response mode and narrow the window, I will see scroll bars. We should wrap the topics until we get to the mobile layout, where the drawer content is hidden.

**Comment by MAbdurrehman12** [comment]
@pdpinch I have created the PR for this but I wonder this might be a breaking change for a few dimensions. As it will be good for **width: 1280px** (Laptop with MDPI screen),  but we have a range of width from **992px to 1250px** where the course info is unreadable and horizontal scroll will come in handy here.
For example: 

for width:992px
![image](https://user-images.githubusercontent.com/93309234/149117748-8edafbab-f0ae-487c-8c5f-17b62c7d9216.png)


for width:1250px
![image](https://user-images.githubusercontent.com/93309234/149117878-c843ddc1-12ac-4440-9de7-0274693be0f3.png)

If it's important for 1280px then we can only remove the horizontal scroll for this dimension and not for the dimension range stated above.

What are your thoughts?

**Comment by pdpinch** [comment]
Yeah, that's not great. Can we let the content in the drawer wrap at that width?

Or, what happens if we let the drawer go to the mobile presentation at that width? I think it becomes a button, but I can't remember.

**Comment by MAbdurrehman12** [comment]
Yeah, I tried to wrap the content in that width but it became difficult, (1-2 words per line were not looking user friendly).

yes, you are right, it becomes a button in mobile representation but that occurs on 991px width, which I believe is the default breakpoint for medium screens. I'm not sure whether it's a good practice to change the default breakpoint or not. Our issue is from 992px to 1250px.
What do you think?

**Comment by MAbdurrehman12** [comment]
I guess if the content is not being adjusted in this drawer section then a horizontal scroll makes sense but if the content is being adjusted in the section then a horizontal scroll doesn't make sense and can be considered a bug

**Comment by pdpinch** [comment]
Is it possible to only show the horizontal scroll when the content is being adjusted, and it doesn't fit?

**Comment by MAbdurrehman12** [comment]
Yes, I'll update it to only show the horizontal scroll when the content doesn't fit. 
If the content fits, then horizontal scroll will not be shown.
