### ISSUE TITLE
OCW Sandwich menu

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#26]
We need a working sandwich menu in mobile

### Design

https://projects.invisionapp.com/d/main?origin=v7#/console/18552410/447796539/preview?scrollOffset=2381.111083984375

### Acceptance Criteria

- [ ] search box
- [ ] Give link
- [ ] about link
- [ ] help & faq link
- [ ] contact us link

**Comment by alicewriteswrongs** [comment]
I believe this was fixed by #310
