### ISSUE TITLE
remove coursemedia hack

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-hugo-themes#265]
In https://github.com/mitodl/ocw-hugo-themes/pull/264, we added a hack to replace `/courses` with `/coursemedia` and make sure it only happened on the EC2 based OCW Next build servers.  Once these servers are decommissioned, this hack should be removed.

**Comment by pdpinch** [comment]
Is this still an issue?

**Comment by gumaerc** [comment]
@pdpinch The hack still needs to be removed, but isn't causing any issues at the moment.  I'd like to assign this to myself and leave it up as a reminder to deal with it.  I'll removed "blocked" because it can actually be removed at this point without breaking anything.
