### ISSUE TITLE
ocw-www: course collections

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#280]
As an OCW staff member, I'd like to be able to create and publish a collection of courses so I can, for example, publish a list of Open Learning Library courses. 

#### Designs and Mockups

Similar to the video gallery design at List of documents (PDFs) from https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/461095857/preview?scrollOffset=497.20001220703125 but with course thumbnails instead of video thumbnails. 

#### Related issues

- depends on adding course collections to project: https://github.com/mitodl/ocw-hugo-projects/issues/101

**Comment by alicewriteswrongs** [comment]
The UI for this is very similar to the UI we show for the search results, so I'm going to look into what's required to re-use that here.
