### ISSUE TITLE
Buy at MIT Press image is missing 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#289]
### Steps to Reproduce

The image link to `/images/mp_logo.gif` is broken on https://ocwnext.odl.mit.edu/courses/21g-049-french-photography-spring-2017/pages/assignments/presentations-and-sources/ 

TBD. We should consider replacing the legacy image: <image src="https://ocw.mit.edu/images/mp_logo.gif">

### Expected Behavior

- there should be a (black) button

### Actual Behavior

We only see the alt text. 

### Related Issues

We might want to consider redesigning this button. It's quite small, and might be rendered as text with styling or an SVG. 

### Screenshot or Screencast

![image](https://user-images.githubusercontent.com/430126/144102898-e829c50f-19dd-46a0-83a3-535c01adcfe3.png)

![image](https://user-images.githubusercontent.com/430126/144102928-bbe8f943-f90e-4e5f-8470-49ebd5a640f5.png)

**Comment by MAbdurrehman12** [comment]
@pdpinch For this, I guess I need to have access to the content of this course.
Please correct me if I'm mistaken

**Comment by pdpinch** [comment]
The legacy course is here: https://ocw.mit.edu/courses/global-languages/21g-049-french-photography-spring-2017/assignments/presentations-and-sources/

We need to add https://ocw.mit.edu/images/mp_logo.gif to the [course theme](https://github.com/mitodl/ocw-hugo-themes/tree/main/course) in a way that it can be loaded by https://ocwnext.odl.mit.edu/courses/21g-049-french-photography-spring-2017/pages/assignments/presentations-and-sources/

@gumaerc may have some advice on where to put it and how to test it.

**Comment by MAbdurrehman12** [comment]
Okay, Thanks

**Comment by pdpinch** [comment]
PR #336 didn't seem to work. I'm reopening this.

**Comment by pdpinch** [comment]
Looks like the image made it onto the RC server, but we have a styling problem: #477

**Comment by MAbdurrehman12** [comment]
> Looks like the image made it onto the RC server, but we have a styling problem: #477 


Okay, I'll look into it
