### ISSUE TITLE
CHP: styling update

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#29]
See notes in https://docs.google.com/document/d/1cmKKed8-q6pR3SmA1tKB0_iPhKOTtviVXDpsn7tMvdM/edit?ts=6053bf9d for details. 

#### Acceptance Criteria:

- [ ] more padding between left nav items and reveal (`+`) button
- [ ] decrease the padding around course features
- [ ] left align the course image
- [ ] Move the “Read More” link closer to the above text and remove the arrow next to it.
- [ ] Move the expand and collapse arrow closer to the Course Info section header.
- [ ] top-align course feature icons
- [ ] top-align the left nav, course image, and course description

**Comment by noisecapella** [comment]
Should any changes be made to the indented items? 
![Screenshot from 2021-06-01 14-07-11](https://user-images.githubusercontent.com/863262/120370539-b3362680-c2e2-11eb-90b2-e4e20b53aeae.png)

**Comment by noisecapella** [comment]
Should all course features be displayed in one line? If not should they be in columns? The doc only says to space them out:
![Screenshot from 2021-06-02 07-35-13](https://user-images.githubusercontent.com/863262/120473506-15d80280-c375-11eb-827c-859530747141.png)

**Comment by noisecapella** [comment]
@pdpinch @abdulkdawson any thoughts on these questions?

**Comment by pdpinch** [comment]
Some courses have too many for one line, e.g. https://ocwnext.odl.mit.edu/courses/6-00sc-introduction-to-computer-science-and-programming-spring-2011/

Columns makes sense to me.

**Comment by noisecapella** [comment]
@pdpinch FYI The PR which just merged should address everything, except that I didn't address "Expand the features themselves to decrease wrapping" from the google doc since it was unclear what we need to do there. I left the feature columns as it was before is which is 4 columns for desktop and 2 for mobile.

**Comment by abdulkdawson** [comment]
@noisecapella I second what Peter said.
