### ISSUE TITLE
ocw-www educator page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#307]
As a user, I'd like to find out more about OCW features that support educators

#### Designs and Mockups

desktop: https://invis.io/7Y12598HHF6E#/462148864_Educators_Start_Here
mobile: TBD, although I don't think it requires anything special 
copy: https://docs.google.com/document/d/1DTD0cHXB_n3UH1HZwyD8adFOfrgxfY_zSzY5pTTyKyE

#### Acceptance Criteria:

- [ ] for now, this should all be part of the ocw-www theme. In the future, we may consider exposing some of it through studio. 
- [ ] As much as possible, styles should follow existing styles (e.g. fonts & colors), especially those added in #303 
- [ ] One long, scrolling page
- [ ] on-page nav should stay sticky, at top of viewport when user scrolls down (mobile UX TBD)
- [ ] clicking on item in on-page nav should smooth-scroll down to the appropriate section, not jump. 
- [ ] SRC images should be available in InVision
- [ ] video at https://www.youtube.com/watch?v=7UJ4CFRGd-U
- [ ] Update the ocw-www home page to link "Educators Start Here" to this page

**Comment by MAbdurrehman12** [comment]
@pdpinch  
Currently, I have redirected all the **non ocw.mit.edu links** in new tab and all the **ocw.mit.edu links** in the same tab.
Is there any convention to follow or it is fine this way? 

Should we redirect this to Chalk Radio Podcast youtube or there's any other link?
![image](https://user-images.githubusercontent.com/93309234/147763145-2694ed8d-fb03-4a1b-9d6b-a4c48d391c39.png)

**Comment by MAbdurrehman12** [comment]
@pdpinch If we scroll to a particular section, should its navbar item be highlighted (made active) automatically? 
(e.g: If I scroll from "Welcome" section to "Discover OER" section, then "Welcome" link in the navbar becomes inactive, and "Discover OER" link becomes active.)

**Comment by pdpinch** [comment]
I think that's a good idea, if it's not too much work.

**Comment by MAbdurrehman12** [comment]
> I think that's a good idea, if it's not too much work.

Sure, I'll look into it
