### ISSUE TITLE
Section link should remain highlighted on subsections which are not part of the sidebar

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-hugo-themes#31]
If you go to https://ocwnext.odl.mit.edu/courses/18-01-single-variable-calculus-fall-2006/pages/readings/ you can see that "Readings" is not highlighted on the sidebar. If you go to the corresponding page in the legacy site, it is highlighted in the sidebar: https://ocw.mit.edu/courses/mathematics/18-01-single-variable-calculus-fall-2006/readings/course-reader/

**Comment by pdpinch** [comment]
@Wassaf-Shahzad I'm not sure if this is the same issue that you are fixing in #345

**Comment by Wassaf-Shahzad** [comment]
> https://ocwnext.odl.mit.edu/courses/18-01-single-variable-calculus-fall-2006/pages/readings/

Yes, my PR will fix this issue as well

**Comment by Wassaf-Shahzad** [comment]
https://github.com/mitodl/ocw-hugo-themes/pull/352 This commit will resolve this issue

**Comment by Wassaf-Shahzad** [comment]
@pdpinch  This issue has been resolved my the following PR https://github.com/mitodl/ocw-hugo-themes/pull/352

**Comment by Wassaf-Shahzad** [comment]
> @pdpinch This issue has been resolved my the following PR #352

@pdpinch  Can we close this issue ?

**Comment by pdpinch** [comment]
I'm closing it, but you could have too. Thank!
