### ISSUE TITLE
Update CSS for about and educator pages

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#328]
CSS updates for the about and educator pages

> The css is very targeted and could append to the end of the current stylesheet to have these changes hold, however the developers should take this and break it out/make changes to the existing stylesheet with the changes I’ve made - which ever is easiest. You’ll see the margins/spacing and other mobile stuff corrected. 

CSS file at https://drive.google.com/drive/u/1/folders/1S3-tJ5iBJ0yTk5IkAOHN4gtXa9_7oUew

#### Designs and Mockups

https://drive.google.com/file/d/1iRd_s_IQ41ib7q6epr_LSvKUbwK5uM4M/view?usp=sharing
https://drive.google.com/file/d/1FNC2t0pM7SjL8lSbsg7MMFXtD9OfYlJw/view?usp=sharing

**Comment by pdpinch** [comment]
@MAbdurrehman12 If possible, try to re-use the CSS as much as possible, instead of having CSS for specific ids.

**Comment by MAbdurrehman12** [comment]
> @MAbdurrehman12 If possible, try to re-use the CSS as much as possible, instead of having CSS for specific ids.

Yeah, I also try to follow the approach of making generic css and reusing it wherever required.

**Comment by MAbdurrehman12** [comment]
btw, if we give preference to bootstrap (which we are already using), it will minimize CSS
