### ISSUE TITLE
Contact Us page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#340]
As a user, I'd like a way to contact the OCW team for questions that aren't covered in the Help & FAQ section (ZenDesk Help Center)

As a OCW team member, I'd like to discourage repetitive questions over email. 

#### Designs and Mockups

https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/462875131/comments?scrollOffset=901.5

#### Acceptance Criteria:

- [ ] page location should be /contact
- [ ] Use the same form back-end service that we currently use on https://ocw.mit.edu/about/contactus/ It looks like the JavaScript embed code is 
```
<div id="wufoo-z6wocqd1ghkc5f">Fill out my <a href="https://mitocw.wufoo.com/forms/z6wocqd1ghkc5f">online form</a>.</div>
<script type="text/javascript"> var z6wocqd1ghkc5f; (function(d, t) { var s = d.createElement(t), options = { 'userName':'mitocw', 'formHash':'z6wocqd1ghkc5f', 'autoResize':true, 'height':'803', 'async':true, 'host':'wufoo.com', 'header':'hide', 'defaultValues':'Field113=' + encodeURIComponent(document.referrer), 'ssl':true }; s.src = ('https:' == d.location.protocol ?'https://':'http://') + 'secure.wufoo.com/scripts/embed/form.js'; s.onload = s.onreadystatechange = function() { var rs = this.readyState; if (rs) if (rs != 'complete') if (rs != 'loaded') return; try { z6wocqd1ghkc5f = new WufooForm(); z6wocqd1ghkc5f.initialize(options); z6wocqd1ghkc5f.display(); } catch (e) { } }; var scr = d.getElementsByTagName(t)[0], par = scr.parentNode; par.insertBefore(s, scr); })(document, 'script'); </script>
```

#### Out of Scope

- field validation should be provided by wufoo.com

**Comment by MAbdurrehman12** [comment]
@pdpinch "Use the same form back-end service": By this, initially I thought that we have to use wufoo API for form submission only and I created a custom form with google captcha from scratch but then I found out, from the code snippet you provided, that form will also be rendered by wufoo. However, I have a few things in mind regarding the wufoo form: 

1- In order to customize the form, i.e: changing input fields name, sizes, error, success messages, I believe I will need access to https://mitocw.wufoo.com/ in order to make changes to the form but I'm not sure as I haven't worked with wufoo, though I had a quick look into its documentation.

2- Wufoo form takes a few seconds to render so an empty space is shown till then. (This is also there in the legacy site), I think we can improve this somehow. 

3- Wufoo API also takes some time to give response, and in the meantime, we don't have any particular loader etc, maybe this can also be handled by form customization. 

Do you have any thoughts on this?

**Comment by MAbdurrehman12** [comment]
@pdpinch I was also thinking of form submissions consistency among contact page and newsletter page, as both pages have different 3rd parties so, for now, their error handling and form submission is different from each other.
Personally I liked mailchimp more as it has more flexibility for customization.

Do you have any thoughts on this too?

**Comment by pdpinch** [comment]
Thanks. I'll see about getting access to the service.

**Comment by pdpinch** [comment]
The contact form needs to forward the email to another inbox where it’s processed and stored in a database (not managed by our team).

I don’t know if mailchimp can do simple forwarding like that, but I guess it’s worth some investigation.

**Comment by MAbdurrehman12** [comment]
> The contact form needs to forward the email to another inbox where it’s processed and stored in a database (not managed by our team). I don’t know if mailchimp can do simple forwarding like that, but I guess it’s worth some investigation.

I believe Mailchimp can also be integrated here and it can forward the contact form data to another email (to your admin or support team), but not sure what you meant by "stored in database"?

**Comment by pdpinch** [comment]
I sent you an invite to wufoo forms, so you can edit the form. Or, even better, create a new form, since this is already in use on ocw.mit.edu. 

I looked around mailchimp a bit, but couldn't figure out 1) how to invite you to the account or 2) how to forward the form results to a single email address.

**Comment by pdpinch** [comment]
After doing some more testing, it seems like everything is functional, it just doesn't look great. 

I think we should merge this as is, and come back to it later to improve the styling, so we can focus on more important MVP features.

**Comment by MAbdurrehman1** [comment]
> After doing some more testing, it seems like everything is functional, it just doesn't look great. 
> 
> 
> 
> I think we should merge this as is, and come back to it later to improve the styling, so we can focus on more important MVP features. 

Okay, sure.
Have you reviewed the code too? If not then I guess we can get the code reviewed and merge it!

**Comment by MAbdurrehman12** [comment]
> After doing some more testing, it seems like everything is functional, it just doesn't look great. 
> 
> 
> 
> I think we should merge this as is, and come back to it later to improve the styling, so we can focus on more important MVP features. 

Okay, sure.
Have you reviewed the code too? If not then I guess we can get the code reviewed and merge it!

**Comment by pdpinch** [comment]
I have not reviewed it. @Wassaf-Shahzad can you review?
