### ISSUE TITLE
Add HTML container file to resource data.json template

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#346]
For [search indexing](https://github.com/mitodl/open-discussions/issues/3486#issuecomment-1013434948), and for resource collections, it would be useful to include the URL for the HTML page that embeds a resource in the data template for the resource. 

For example, in the data file https://ocwnext-rc.odl.mit.edu/courses/4-112-architecture-design-fundamentals-i-nano-machines-fall-2012/resources/mit4_112f12_prjct1-draw/data.json it would useful to have a field with the value "/courses/hst-950j-medical-computing-spring-2003/resources/assignment1"

**Comment by pdpinch** [comment]
@abeglova @alicewriteswrongs I think this might be a duplicate issue for work you already did? If so, please close it.

**Comment by alicewriteswrongs** [comment]
That data is not currently found in the `data.json` file for a given resource. Given the change I made recently to add `content_map.json` (#400) it would be possible I think to get that URL from there, but that would require fetching that file as well.

**Comment by pdpinch** [comment]
Let me ask this question another way, would search, or list UX benefit from having URLs for resource HTML containers?

**Comment by pdpinch** [comment]
Search and course lists seem to work great, so I don't think we need this anymore.
