### ISSUE TITLE
Aspect ratio property not working on Safari

### ISSUE THREAD

**Issue by Wassaf-Shahzad** [mitodl/ocw-hugo-themes#390]
### Steps to Reproduce
Apparently css property aspect ration isn't available on  some versions of safari and Firfox nightly. Which causes the youtube video to be cutoff in above mentioned browsers

### Expected Behavior
The video frame should not be cutoff

### Actual Behavior
The video tab is cutoff

### Related Issues
Related commit https://github.com/mitodl/ocw-hugo-themes/commit/821bf2418f1a9bf02549619e0ae2a137582e29af

**Comment by pdpinch** [comment]
@Wassaf-Shahzad do you know if this is still an issue? If so, can you specify the version of Safari and/or Firefox that are affected?
