### ISSUE TITLE
Mobile: “Browse course materials” menu is missing from 2nd level page 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#394]
### Steps to Reproduce

1. Set your browser to a mobile width
2. Visit https://ocwnext.odl.mit.edu/courses/mas-962-special-topics-new-textiles-spring-2010/
3. Use the "Browse course materials" menu at the top of the page to navigate to "Readings Lectures & Tutorials"

### Expected Behavior

- The "Browse Course materials" menu should be visible on this page as well, so you can continue navigating the course. 

### Actual Behavior

- The "Browse Course materials" menu is missing 

### Related Issues

- mobile: browse menu should be sticky

### Screenshot or Screencast

![image](https://user-images.githubusercontent.com/430126/151736511-a4f2d86f-65f6-49e0-adf9-4da8e89ffe14.png)

**Comment by MAbdurrehman12** [comment]
@Wassaf-Shahzad You can assign this issue to yourself as your PR will fix it
