### ISSUE TITLE
course `cms.611j-fall-2014` won't build

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#402]
### Steps to Reproduce

1. Check out the course repo at https://github.mit.edu/ocw-content-rc/cms.611j-fall-2014
2. Build it

### Expected Behavior

- Normal course build, with a CHP

### Actual Behavior

- I don't know, but when studio builds this course, it looks like https://ocw-draft-qa.global.ssl.fastly.net/courses/cms-611j-creating-video-games-fall-2014/ 

<img width="1663" alt="image" src="https://user-images.githubusercontent.com/430126/152065030-5c4cf02f-bcbd-4702-917f-59311dbdf54d.png">

**Comment by pdpinch** [comment]
I spoke with @gumaerc a bit about this, and it seems like it's due to a bug in the course publishing pipeline, which maybe we should discuss with @mbertrand 

It seems like, after the course site is published, we are merging the course site directory with the contents of the `open-learning-course-data` S3 bucket. I'm not sure why we're doing that, but since some directories contain `index.html` files, we have to find another solution.

**Comment by mbertrand** [comment]
This issue might be relevant? https://github.com/mitodl/ocw-studio/issues/829

**Comment by MAbdurrehman12** [comment]
@pdpinch Carey proposed some solutions yesterday, I assume you guys already have them under discussion. 
If not, then I can go on and summarise them here.
I'm also not sure whether I'm the right assignee of this issue.

**Comment by pdpinch** [comment]
This was fixed, for the time being by https://github.com/mitodl/ocw-studio/pull/970
