### ISSUE TITLE
Inline links should be blue, but this one is black

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#405]
### Steps to Reproduce

Compare the links on this page (correct):

https://ocwnext-rc.odl.mit.edu/courses/12-001-introduction-to-geology-fall-2013/pages/lecture-notes-and-slides/

to the links on this page (incorrect):

https://ocwnext.odl.mit.edu/courses/11-312-engaging-community-models-and-methods-for-designers-and-planners-spring-2020/pages/syllabus/

### Expected Behavior

- inline links should be blue

### Actual Behavior

- sometimes they are black

**Comment by Wassaf-Shahzad** [comment]
@pdpinch 
The following PR https://github.com/mitodl/ocw-hugo-themes/pull/397 closes this issue as well 
 
<img width="729" alt="Screenshot 2022-02-02 at 2 40 36 PM" src="https://user-images.githubusercontent.com/87968618/152130414-9d27f5ba-9401-406d-a956-9cb5f07a8112.png">

<img width="729" alt="Screenshot 2022-02-02 at 2 40 28 PM" src="https://user-images.githubusercontent.com/87968618/152130429-eb6cd098-c76a-4024-bb13-61c9e55c0ff8.png">
