### ISSUE TITLE
missing table header styling

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#406]
### Steps to Reproduce

Compare this table header (blue, all caps, correct):

https://ocwnext-rc.odl.mit.edu/courses/12-001-introduction-to-geology-fall-2013/pages/lecture-notes-and-slides/

<img width="632" alt="image" src="https://user-images.githubusercontent.com/430126/152102126-90d36bcc-f83e-48bd-9f99-d695cd731e00.png">

to this table header (in correct):

https://ocwnext.odl.mit.edu/courses/8-01sc-classical-mechanics-fall-2016/pages/syllabus/

<img width="660" alt="image" src="https://user-images.githubusercontent.com/430126/152102194-3d03966c-ff7c-4213-8677-65232745fee6.png">

### Expected Behavior

- table headers should be consistent, with blue backgrounds, white text and all caps

### Actual Behavior

- the table header has no styling

**Comment by Wassaf-Shahzad** [comment]
@pdpinch  The following PR https://github.com/mitodl/ocw-hugo-themes/pull/397 will also resolve this issue 

<img width="864" alt="Screenshot 2022-02-02 at 2 20 49 PM" src="https://user-images.githubusercontent.com/87968618/152126547-9c17d88b-d1cb-4556-a0e5-b6dd70b91642.png">
