### ISSUE TITLE
Course collections on the home page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#409]
As a site admin, I'd like to feature certain collections of courses on the OCW home page.

#### Designs and Mockups

<img width="900" alt="image" src="https://user-images.githubusercontent.com/430126/152225654-9ee369eb-9a3f-438c-85f6-0492775b8bc5.png">

from https://invis.io/WG12414QE6S3#/461844036_Home_Cleaned_Up

#### Acceptance Criteria:

- [ ] For MVP, it should display any course collections that are part of the ocw-www site on the home page, in an expanding section based on the design. There is sample content for course collections on the RC server, if that's needed. 

#### Out of Scope

- Site author can select and order which course collections to highlight on the home page

**Comment by Wassaf-Shahzad** [comment]
@pdpinch,
I dont have access to to invision designs inspect mode for some reason. Also can you explain the part `in an expanding section`. Do you want this to be a collapsable ?

**Comment by pdpinch** [comment]
> Do you want this to be a collapsable ?

No. For launch we'll have somewhere between 3 and 6 of these course collections on the home page. Later there may be 12-15. The grey div should be able to scale to work with any number in that range.
