### ISSUE TITLE
CSS: td.h3 style

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#448]
Compare the word "Torsion" on

legacy: https://ocw.mit.edu/courses/mechanical-engineering/2-001-mechanics-materials-i-fall-2006/readings/
nextgen: https://ocwnext.odl.mit.edu/courses/2-001-mechanics-materials-i-fall-2006/pages/readings/

If possible, we should write a narrowly applied style to style these `h3` tags similar to the legacy site.

**Comment by MAbdurrehman12** [comment]
@pdpinch I didn't get this: `we should write a narrowly applied style to style these h3 tags`.

Just to confirm, are you referring to this text? 
![Screenshot 2022-02-17 at 12 57 02 PM](https://user-images.githubusercontent.com/93309234/154430953-b312e9e4-e477-4047-8b85-fff28f699f31.png)

If yes:
then in legacy course, its `font-style` seems to be `italic`, so are you willing to have something like this?  
![image](https://user-images.githubusercontent.com/93309234/154431569-73366878-662c-478a-a70f-cc9948127ee6.png)

and if we also match the `font-family` and `font-weight` like in the legacy course, then we will have something like this:
![image](https://user-images.githubusercontent.com/93309234/154435051-1390c147-5b1d-43b7-800d-5b0b02fc30a7.png)

If yes:
then I guess this change can be applied to all the `h3` tags which are inside `td`. Right?

**Comment by pdpinch** [comment]
That’s is all correct. Thank you for the screenshots. 

I think it’s ok to apply this to all h3 in a td, as long as it doesn’t have side effects on navigation, footer, etc. 

.

**Comment by MAbdurrehman12** [comment]
> Thank you for the screenshots.

No problem

> I think it’s ok to apply this to all h3 in a td, as long as it doesn’t have side effects on navigation, footer, etc.

Sure, I'll look into it
