### ISSUE TITLE
subscript short code adds newline in rendered HTML

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#461]
### Steps to Reproduce

Consider the markdown https://github.mit.edu/mitocwcontent/12.001-fall-2013/blame/main/content/pages/instructor-insights/conveying-the-social-relevance-of-geology.md#L23 and the string `CO{{< sub "2" >}}.`

On https://ocw-draft-qa.global.ssl.fastly.net/courses/12-001-introduction-to-geology-fall-2013/pages/instructor-insights/conveying-the-social-relevance-of-geology/ it appears to be rendered in HTML as:

```
<p>The socially relevant topics we discuss aren’t always related to surface processes. When Prof. Oliver Jagoutz talks about metamorphic reactions in rocks, he discusses a process called serpentinization, which, as it turns out, consumes CO<sub>2</sub>
. There have been proposals to sequester CO<sub>2</sub>
 by encouraging serpentinization reactions in rocks, which would then lock the CO<sub>2</sub>
 in the minerals and take it out of the atmosphere. When he discusses metamorphic rocks, he spotlights this socially relevant application.</p>
```

### Expected Behavior

Since there's no whitespace in the markdown source, it should rendere without a space in the HTML

**Comment by MAbdurrehman12** [comment]
@pdpinch Do we have any other high priority task or should I look into this one?

**Comment by pdpinch** [comment]
This is fine, as long as it doesn't take too long
