### ISSUE TITLE
Add metadata tags for sharing on Facebook

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#464]
As a user sharing an OCW course or page on Facebook, I'd like to see the correct image, title, description and link show up.

Take a look at:
- what has done on the legacy site, old.ocw.mit.edu
- https://github.com/joshbuchea/HEAD
- https://developers.facebook.com/docs/sharing/webmasters/ 
- https://developers.facebook.com/docs/sharing/best-practices

#### Acceptance Criteria:

- [ ] metadata for CHP (course home page)
- [ ] metadata for interior course pages 
- [ ] screenshots of Facebook shares

#### Related Issues

- Twitter metadata
- schema.org metadata 
- LinkedIn share 
- Slack share

**Comment by pdpinch** [comment]
@MAbdurrehman12 what's the status of this?

**Comment by MAbdurrehman12** [comment]
@pdpinch the PR is up for review again
