### ISSUE TITLE
Build error: unrecognized character in shortcode

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#469]
[This error originally came up in concourse](https://cicd.odl.mit.edu/teams/ocw/pipelines/draft/jobs/build-ocw-site/builds/21?vars.site=%2218-100c-real-analysis-fall-2012%22#L6207dba6:6), but I assume it will be reproducible locally. 

```
Error: Error building site: "/tmp/build/d50ae459/course-markdown/content/pages/readings.md:18:4542": unrecognized character in shortcode action: U+0025 '%'. Note: Parameters with non-alphanumeric args must be quoted
```

### Steps to Reproduce

1. Clone course from github: https://github.mit.edu/mitocwcontent/18.100c-fall-2012 -- note that there have been several recent, small changes to this repo. One of them may have caused this error. 
2. Try to build it 

### Expected Behavior

Course builds

### Actual Behavior

course fails to build

**Comment by gumaerc** [comment]
@pdpinch In https://github.com/mitodl/ocw-to-hugo/pull/452, we added support for superscript with the `sup` shortcode.  In `content/pages/readings.md` in the given course, you see:

`{{< sup "<span data-isclosing="false" data-arguments="%5C%22it%5C%22%20" class="legacy-shortcode-sub"></span>" >}}`

This appears to be an issue in `ocw-studio` with editing and legacy shortcodes, as the `legacy-shortcode-${shortcode}` syntax is used in `ocw-studio` in `LegacyShortcodes.ts`.  @alicewriteswrongs any idea why this raw HTML would be written in here?  Is this a turndown issue?

**Comment by pdpinch** [comment]
I dug up the original HTML from the parsed JSON. It doesn't make much sense. 

```
<td>Review of exponential, log, sine, cosine; <em>e<sup><sub>it</sub></sup>= cos(t) </em>+<em> isin(t)</em></td>             
```

This is how it renders on the legacy site:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/430126/155241026-363dd75b-4fee-44e4-a9e8-3fcb26c02b43.png">

I think I'll try just hacking out the `<sub>` tags and see if it makes things happy.

**Comment by gumaerc** [comment]
@pdpinch This looks like something that should be rendered using MathJax, honestly.

**Comment by pdpinch** [comment]
I edited the markdown in the django admin so the course can publish again. There are still minor rendering problems, but I'm closing this issue.
