### ISSUE TITLE
italics not rendering correctly in table cell

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#490]
### Steps to Reproduce

1. Check out the course at https://github.mit.edu/mitocwcontent/res.18-001-spring-2005/
2. build it
3. Take a look at the page `/pages/instructors_manual/` 

### Expected Behavior

- The text at the start of the first regular cell (not the header), should be in italics, i.e. _1: Introduction to Calculus_ 

### Actual Behavior

- The text is rendering as \_1: Introduction to Calculus\_

**Comment by pdpinch** [comment]
@alicewriteswrongs or @ChristopherChudzicki is it possible to include whitespace when ckeditor saves out the table shortcodes?

**Comment by pdpinch** [comment]
@alicewriteswrongs I guess you have a PR to fix this now?

**Comment by alicewriteswrongs** [comment]
yes, here in Studio: https://github.com/mitodl/ocw-studio/pull/1081

based on my testing I don't think any change will be necessary in the theme

**Comment by pdpinch** [comment]
Can this be closed?

**Comment by pdpinch** [comment]
Looks like this is working now, although we might need @Wassaf-Shahzad's solution for other cases like #501 and pages like https://ocw-draft-qa.global.ssl.fastly.net/courses/18-06sc-linear-algebra-fall-2011/pages/ax-b-and-the-four-subspaces/column-space-and-nullspace/
