### ISSUE TITLE
Home: remove all "coming soon" pop-ups

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#524]
We should have working hrefs for all links on the home page, about page and educator page

#### Acceptance Criteria:

- [ ] "Get Started" on the home page should link to ZenDesk, https://mitocw.zendesk.com/hc/en-us/categories/4414679122971-Get-Started-with-MIT-OpenCourseWare

**Comment by Wassaf-Shahzad** [comment]
@pdpinch 
The PR https://github.com/mitodl/ocw-hugo-themes/pull/522 will handle coming soon pop ups for the one link in home page.
However there are still anchor tags  in educator page which have the coming soon pop up which are 
- Zero Textbook Cost” (ZTC) initiatives
- Find open online textbooks from MIT
- Browse MIT instructor interviews by department

**Comment by pdpinch** [comment]
I opened a new issue #530 for 2 our of 3 of the missing educator links. You can fix them in this PR if you like.
