### ISSUE TITLE
Featured Courses on the OCW Homepage

### ISSUE THREAD

**Issue by dseaton** [mitodl/ocw-hugo-themes#526]
The OCW team would like more control over which courses are featured in the "Carousel". Many of our early design discussions about the OCW homepage involved two carousels, one for "new courses" and one for "featured courses". 

#### Designs and Mockups

We'll add a new carousel with the title "Featured Courses", before "New Courses" 

https://invis.io/SG10KF70VRCB#/448138461_Homepage

#### Acceptance Criteria:

- [ ] Add a metadata section to the ocw-www project, with a relation field labelled "Featured Courses" similar to what we did in https://github.com/mitodl/ocw-hugo-projects/pull/149 
- [ ] If no featured course list has been set, the carousel should be omitted from the home page at build time
- [ ] Add a "Featured Courses" carousel to the home page with the same design as "New Courses" carousel 
- [ ] The carousel should pull the courses from the list specified in the metadata, using static course APIs, as we did in https://github.com/mitodl/ocw-hugo-themes/pull/518

#### Related Issues 

- https://github.com/mitodl/ocw-hugo-themes/issues/551

**Comment by MAbdurrehman12** [comment]
@dseaton @pdpinch
> Add a metadata section to the ocw-www project, with a relation field labelled "Featured Courses" similar to what we did in https://github.com/mitodl/ocw-hugo-projects/pull/149

Should this `Featured Courses` be added as a new section/tab next to course collections, course lists etc (please see image# 1) or somewhere else?
As in [ocw-hugo-projects#149](https://github.com/mitodl/ocw-hugo-projects/pull/149), `Featured Courses List` was added inside `Course Collections`. 

Image# 1
(Maybe we can introduce `Featured Courses` as a tab here but not sure)
<img width="217" alt="image" src="https://user-images.githubusercontent.com/93309234/160393496-c2b83fbe-8ab3-4902-9260-775f0fcfeb2f.png">
