### ISSUE TITLE
More Educator links

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#530]
#### Acceptance Criteria:

- [ ] link "Find open online textbooks from MIT" to `/search/?f=Online%20Textbook`
- [ ] link "Browse MIT instructor interviews by department" to `https://ocwnext.odl.mit.edu/search/?f=Instructor%20Insights`

#### Out of Scope

- Zero Textbook Cost (ZTC) initiatives

**Comment by Wassaf-Shahzad** [comment]
@pdpinch  This can be closed, as it was resolved in PR https://github.com/mitodl/ocw-hugo-themes/pull/522
