### ISSUE TITLE
Update text for the "Giving Section" on the homepage

### ISSUE THREAD

**Issue by dseaton** [mitodl/ocw-hugo-themes#604]
We would like to update the text in the "Giving" section of the OCW homepage.

Old text:
MIT OpenCourseWare is supported through the generosity of people like you, who believe that unlocking knowledge can empower minds.

New text:
[Learn more](https://ocw.mit.edu/pages/why-give/) about how you can help MIT OpenCourseWare share knowledge with the world.

Noting the new text contains a hyper link to the "why give" page.

#### Designs and Mockups
![image](https://user-images.githubusercontent.com/1703442/161583929-d21d30fd-08af-4c5f-8257-64bb87683f03.png)

#### Acceptance Criteria:

- [ ] Text should be changes.
- [ ] A hyperlink to the "why give" page should be in place.

**Comment by MAbdurrehman12** [comment]
The image attached above in Designs and Mockups does not have this `Give Now` heading: 
<img width="878" alt="Screenshot 2022-04-05 at 12 20 25 PM" src="https://user-images.githubusercontent.com/93309234/161700324-f2f85678-f8e2-4d5f-8955-535a21986ee1.png">
Do we have to keep it or remove it?
