### ISSUE TITLE
stand-alone 404 page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#608]
The 404 page was built in studio, but it's served directly from the CDN. The current version has dependencies on versioned CSS and JavaScript files in the theme, which we don't keep indefinitely. 

The 404 page needs to be rewritten to use (minimal) in-line JavaScript and CSS

#### Designs and Mockups

See https://ocw.mit.edu/pages/page-not-found/

#### Acceptance Criteria:

- [ ] If it requires an javascript, add it to the header
- [ ] move all necessary styles out of external css files
- [ ] follow hugo best practices for where to put the file in the theme
- [ ] We only need one of these, so it can go in the ocw-www theme

**Comment by pdpinch** [comment]
@Wassaf-Shahzad where can I tell @mitodl/devops to get the HTML for this page? They will need to add it to the Fastly configuration.

**Comment by Wassaf-Shahzad** [comment]
> @Wassaf-Shahzad where can I tell @mitodl/devops to get the HTML for this page? They will need to add it to the Fastly configuration.

Form the code or by url ?
if by url on rc its available at https://ocwnext-rc.odl.mit.edu/404.html

**Comment by pdpinch** [comment]
When I load the page at https://ocwnext-rc.odl.mit.edu/404.html it still has external js and css dependencies: 

www.a3c26.css
main.a3c26.css
www.a3c26.js
main.a3c26.js

Can those be removed? 

My concern is that those versions of the css and js files are not guaranteed to be permanently available.

**Comment by Wassaf-Shahzad** [comment]
> When I load the page at https://ocwnext-rc.odl.mit.edu/404.html it still has external js and css dependencies:
> 
> [www.a3c26.css](http://www.a3c26.css) main.a3c26.css [www.a3c26.js](http://www.a3c26.js) main.a3c26.js
> 
> Can those be removed?
> 
> My concern is that those versions of the css and js files are not guaranteed to be permanently available.

@pdpinch I can remove our dependency on the css files but not the JS files since they contain code for the header and footer.

I think simplest solution would be to redesign the 404 page with put any use of hugo partials like header and footer.
Since adding these would mean to code for both of this in 404.html rather than only including partials

**Comment by pdpinch** [comment]
> redesign the 404 page without any use of hugo partials like header and footer

That makes sense to me. I don't see why the 404 page would need any JavaScript at all.

**Comment by pdpinch** [comment]
For example, I'm seeing the notification banner on the 404 page currently. We don't need that.

**Comment by pdpinch** [comment]
@Wassaf-Shahzad thanks for merging #716 

I see now that you can open a PR to change the code in the fastly CDN at https://github.com/mitodl/ol-infrastructure/blob/main/src/ol_infrastructure/applications/ocw_site/404.html

Can you use the output of your work in #716 to update the html there?

**Comment by Wassaf-Shahzad** [comment]
> @Wassaf-Shahzad thanks for merging #716
> 
> I see now that you can open a PR to change the code in the fastly CDN at https://github.com/mitodl/ol-infrastructure/blob/main/src/ol_infrastructure/applications/ocw_site/404.html
> 
> Can you use the output of your work in #716 to update the html there?

Sure

**Comment by pdpinch** [comment]
closed via https://github.com/mitodl/ol-infrastructure/pull/915
