### ISSUE TITLE
only load Video and Image Gallery JS when needed

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#648]
We should focus on removing large, rarely-used dependencies from the main course bundle. I.e., all course pages can load the same JS, except video and image-gallery pages should load extra files. (Videojs and its dependencies, along with nanogallery, make up the vast majority of the course JS bundle. It's at least 75%, but I think closer to 90%).

So, IMO:
### Acceptance Criteria
- [x] Only load VideoJS and its dependencies on pages that use VideoJS
- [x] Only load nanogallery2 and its dependencies (there are none) on pages that use it.

### Suggested Approaches
I have two ideas for how to approach this:

1. **At build time:** Put VideoJS in a separate Webpack entrypoint. When building a page, figure out if uses VideoJS. (E.g., if a partial uses VideoJS, have it write to some context like `.Page.Scratch`.). If VideoJS is used, add the appropriate link/script tags.
2. **Dynamic imports:** Webpack is very good at splitting dynamic imports into separate chunks and loading them only as needed. So if the partials call something like `initVideo()`, a function defined in webpack assets whose body includes `import("video.js").then(() => { /* init code */ })`, then `video.js` (and other potential dependencies) would not be loaded unless `initVideo()` is called.

Option 2 seems a little simpler, but Option 1 is nice because it would be determined at built time, and that really seems like it should be the goal.

**Comment by ChristopherChudzicki** [comment]
I would suggest we focus mostly on the JS. The course homepage loads roughly 6 times as much JS as CSS. *This number is based on the branch I'm working on towards #1033*.

Videojs and its dependencies, along with nanogallery, make up the vast majority of the course JS bundle (it's at least 75%, but I think closer to 90%). But those libraries are used on relatively few pages.

IMO, the goal for this issue should be:
### Acceptance Criteria
- [ ] Only load VideoJS and its dependencies on pages that use VideoJS
- [ ] Only load nanogallery2 and its dependencies (there are none) on pages that use it.

### Suggested Approach
A reasonable way to do this would probably be:
1. Create a bundle just for VideoJS
2. Include that bundle only on pages that embed videos.

(and similarly for nanogallery2 and image galleries).

When doing (2), `.Page.Scratch` might be useful: edit the video shortcodes to write `includes_video: true` to `.Page.Scratch`, and include the script on page conditionally based on that. *I have not tested whether this works.*
