### ISSUE TITLE
generic file layout

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-hugo-themes#66]
As a user of the ocw website, I'd like to be able to view metadata on resources other than PDF's on the OCW next website and be able to download them if I want.

#### Designs and Mockups

https://projects.invisionapp.com/d/main?origin=v7#/console/18609637/451119818/preview?scrollOffset=199

#### Acceptance Criteria:

- [ ] Create a layout meant to be used for viewing metadata about files and downloading them in the `course` theme, potentially `course/layouts/course/file.html`
- [ ] The layout iterates a metadata property, something like `file_metadata` and displays the metadata on the page as in the design
- [ ] The layout renders a Download button linking to the `file_location` front matter property

**Comment by pdpinch** [comment]
@gumaerc can this be closed?

**Comment by gumaerc** [comment]
This was resolved in https://github.com/mitodl/ocw-hugo-themes/pull/172
