### ISSUE TITLE
ocw-www: use the most recently modified notification

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#695]
As an ocw-www author, I'd like the most recently modified notification to be displayed (and other notifications to be hidden) 

Based on [this discussion](https://github.com/mitodl/hq/discussions/46#discussioncomment-2748542), we can sort using [ByLastmod](https://gohugo.io/templates/lists/#by-last-modified-date) to display the most recently modified notification.

**Comment by Ferdi** [comment]
There is only 1 notification shown at a time, by design.   If you want to change , you can edit the one notification that is there. it's short.
