### ISSUE TITLE
Missing/incomplete code section

### ISSUE THREAD

**Issue by MAbdurrehman12** [mitodl/ocw-hugo-themes#704]
### Steps to Reproduce

- Go to this [page](https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/pages/in-class-questions-and-video-solutions/lecture-2/) 
- Verify that the code in different code sections is incomplete/missing

### Expected Behavior

- Code should be complete in every code section

### Actual Behavior

- Code in different code sections is incomplete/missing

### Screenshot or Screencast

<img width="676" alt="image" src="https://user-images.githubusercontent.com/93309234/170487041-851ec60e-4e59-4766-8de5-7c32a06924ba.png">

**Comment by MAbdurrehman12** [comment]
@pdpinch It looks like the code is complete in legacy course content. 

After fetching the `legacy course` and building it locally, all the pages have complete code sections. 
Even when I import the course to `studio` locally, it is imported successfully with complete code sections and after publishing the course from my `local studio setup` to my `local Github organization`, everything is fine. Code sections, in `lecture 2-9`, are complete (not missing)

e.g: 
<img width="644" alt="image" src="https://user-images.githubusercontent.com/93309234/170684960-1e017777-f49f-4f44-b223-81b555ee89b3.png">

So I'm not sure how the code is missing on `RC` and `PROD`, despite the fact that everything is fine locally. Maybe there was an issue during `import` or maybe this was a bug related to code blocks which has already been fixed, not sure.

Since the pages are few which have these missing code sections so maybe this is something that can be fixed manually. But I'm trying to find out what the actual reason of this issue is.

@gumaerc @mbertrand Incase, you also have some thoughts to share regarding this.

**Comment by pdpinch** [comment]
I'm willing to ask someone from the OCW team to manually fix these, but it would help if we knew how many pages were affected. Is there some way to find them all -- maybe by diffing the the markdown published from a local copy to the markdown in https://github.mit.edu/mitocwcontent/6.0001-fall-2016 ?

**Comment by MAbdurrehman12** [comment]
I think pages from lecture-2: `/pages/in-class-questions-and-video-solutions/lecture-2/` to lecture-9: `pages/in-class-questions-and-video-solutions/lecture-9/` are affected. 

I'll also do the comparison with the local copy to re-confirm this.

**Comment by pdpinch** [comment]
A count or list of the pages would be helpful, to evaluate whether to fix this by hand or do something more complicated.

**Comment by MAbdurrehman12** [comment]
> A count or list of the pages would be helpful, to evaluate whether to fix this by hand or do something more complicated.

For this course, following pages have incomplete/missing code:
- https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/pages/in-class-questions-and-video-solutions/lecture-2/
- https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/pages/in-class-questions-and-video-solutions/lecture-3/
- https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/pages/in-class-questions-and-video-solutions/lecture-4/
- https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/pages/in-class-questions-and-video-solutions/lecture-5/
- https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/pages/in-class-questions-and-video-solutions/lecture-7/
- https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/pages/in-class-questions-and-video-solutions/lecture-8/
- https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/pages/in-class-questions-and-video-solutions/lecture-9/

Just wondering, how can we identify if there are more courses with this issue?

**Comment by pdpinch** [comment]
> how can we identify if there are more courses with this issue?

I don't know, unless we can find some pattern to how they are truncated.

**Comment by MAbdurrehman12** [comment]
> Could you share your github export of the course with me, so I can compare?

Will a zip file work for you? 
If yes, then PFA.
[6.0001-legacy.zip](https://github.com/mitodl/ocw-hugo-themes/files/8887902/6.0001-legacy.zip)

**Comment by gumaerc** [comment]
I looked into this, and the reason this is rendering this way is apparent when you look at the source HTML from Plone:

```
<pre class="edx">
    <code>pset_time = 15</code>
    <code>sleep_time = 8</code>
    <code>print(sleep_time &gt; pset_time)</code>
    <code>derive = True</code>
    <code>drink = False</code>
    <code>both = drink and derive</code>
    <code>print(both)</code>
</pre>
```

If we look at `turndown.js` in `ocw-to-hugo`, `pre` elements are converted to code blocks via a rule that we define.  Turndown already has a built in rule that all `code` elements should be turned into inline code blocks with the single backtick.  Therefore, a PR in `ocw-to-hugo` will be needed to make sure that `code` elements inside `pre` elements are treated as plain text.

**Comment by gumaerc** [comment]
@MAbdurrehman12 I put up a PR [here](https://github.com/mitodl/ocw-to-hugo/pull/519) to fix this issue in `ocw-to-hugo`, but after it merges we will need a migration in `ocw-studio` to selectively bring in the fixed content.

**Comment by MAbdurrehman12** [comment]
Great!
Thanks @gumaerc

**Comment by MAbdurrehman12** [comment]
@gumaerc Did we run the migration in studio?

**Comment by gumaerc** [comment]
@MAbdurrehman12 it's been a while, but no, no migration has been run here to import these fixed code blocks. Looking at the `ocw-to-hugo` PR I did there, it's possible that the scope is limited to those few courses I use in the testing instructions. A migration here would need to look at the content of pages in `ocw-studio` one by one and compare them to the `ocw-to-hugo` output. So many manual edits have happened at this point that it may be a waste of time to try and write a migration to do it at this point. Instead, it might be better for someone to look at the `ocw-to-hugo` output for the courses in question and diff it against the markdown put into `mitocwcontent`. Then, we should likely manually update anywhere where there are problematic code blocks rather than trying to write a migration. This all depends on the scope though. Diffing may prove difficult because of all the manual edits that have been made in studio at this point.

**Comment by MAbdurrehman12** [comment]
@pdpinch I had a chat with Carey regarding this issue, and it looks like we don't have complete code in the content hence this needs to be fixed manually rather than through a migration. 
I can go on the fix these [pages](https://github.com/mitodl/ocw-hugo-themes/issues/704#issuecomment-1145002800) manually on RC and once that is verified, we can do the same on production.

**Comment by MAbdurrehman12** [comment]
@pdpinch I have manually fixed the missing code sections on RC. 
These are the pages that have been fixed. Can you please have a look? 
If all is okay then I think we can fix these in production too.

- https://live-qa.ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/pages/in-class-questions-and-video-solutions/lecture-2/
- https://live-qa.ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/pages/in-class-questions-and-video-solutions/lecture-3/
- https://live-qa.ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/pages/in-class-questions-and-video-solutions/lecture-4/
- https://live-qa.ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/pages/in-class-questions-and-video-solutions/lecture-5/
- https://live-qa.ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/pages/in-class-questions-and-video-solutions/lecture-7/
- https://live-qa.ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/pages/in-class-questions-and-video-solutions/lecture-8/
- https://live-qa.ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/pages/in-class-questions-and-video-solutions/lecture-9/

**Comment by pdpinch** [comment]
These look good except: 

[Lecture 8](https://live-qa.ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/pages/in-class-questions-and-video-solutions/lecture-8/) has some exposed backticks in the multiple choice problems. If we can't that to render correctly, I would say just remove the backticks. 

[Lecture 5](https://live-qa.ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/pages/in-class-questions-and-video-solutions/lecture-8/) is just a mess, probably due to a similar issue to lecture 8. 

If it takes you more than 15m to fix these, I would say close this issue and open a new one for the remaining problems.

**Comment by MAbdurrehman12** [comment]
Okay, I'll look into it

**Comment by MAbdurrehman12** [comment]
Closing this issue as this has been fixed on RC and PROD.
