### ISSUE TITLE
Why give page is not mobile friendly

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#718]
### Steps to Reproduce

1. See https://ocw.mit.edu/pages/why-give
2. You can do a live test of the page using Google's mobile friendly tool at https://search.google.com/test/mobile-friendly?hl=en

Presumably these results should be the same as Lighthouse tests, but I haven't checked. 

### Expected Behavior

page is rated "mobile friendly"

### Actual Behavior

- Text too small to read
- Clickable elements too close together 
- Content wider than the screen 
- I'm not sure why this page is singled out. None of the other (hugo-published) pages get these result.

**Comment by Wassaf-Shahzad** [comment]
@pdpinch The lighthouse scores seem to differ (somewhat)
<img width="1438" alt="Screenshot 2022-06-02 at 3 20 10 PM" src="https://user-images.githubusercontent.com/87968618/171609399-018b6721-0dfa-45b0-821b-07eafd2214cf.png">

**Comment by pdpinch** [comment]
Closing the loop on this, I tested with https://search.google.com/test/mobile-friendly/result?id=rnAXJprJ9D9U_EgFaBctWA&hl=en and Google gave it a pass.
