### ISSUE TITLE
Compact Search 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#769]
As a search user, I'd like to have an option to view search results in a compact form, so I can see more results per page, and so I can focus on course numbers and titles (in course search) and resource titles and courses titles (in resource search) 

#### Designs and Mockups

[compact course search, updated 6/23 ](https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/467901664/preview)
[compact resource search, updated 6/23](https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/467901663/preview)
[expanded course search, with consistent colors](https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/467901615/preview)

#### Acceptance Criteria:

- [ ] Add a control for switching between expanded and compact search
- [ ] hide the control for now, so we can test compact search before releasing it to users (essentially, this is a UI-based feature toggle) 
- [ ] include the control setting in the URL so we can share compact search results, and so the setting will during a search session

#### Out of Scope

- Should we set a cookie with the search preference?

**Comment by abeglova** [comment]
This is done but we hid the toggle to change the view so it's not available to all users. It's available by adding u=compact to ocw search uls. https://ocw.mit.edu/search/?u=compact

**Comment by pdpinch** [comment]
@abeglova can you open a PR to make the switch visible?

**Comment by pdpinch** [comment]
Can we close this now?

Where was the PR to make the button permanently visible?

**Comment by abeglova** [comment]
Here is the PR for making the button permanently visible https://github.com/mitodl/ocw-hugo-themes/pull/953
