### ISSUE TITLE
Webpack Issue with Node v18.4.0

### ISSUE THREAD

**Issue by pt2302** [mitodl/ocw-hugo-themes#778]
### Steps to Reproduce

Run `npm run start:course` with a valid `.env` file. Note that this error happens with Node v18.4.0 (the latest stable version), but not Node v16.5.1 LTS.

### Expected Behavior

The course website is generated and served locally.

### Actual Behavior

The command fails with the errors:

```
[start:webpack] Error: error:0308010C:digital envelope routines::unsupported
[start:webpack]   at new Hash (node:internal/crypto/hash:67:19)
[start:webpack]   at Object.createHash (node:crypto:133:10)
[start:webpack] opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[start:webpack]  library: 'digital envelope routines',
[start:webpack]  reason: 'unsupported',
[start:webpack]  code: 'ERR_OSSL_EVP_UNSUPPORTED'
```

**Comment by Wassaf-Shahzad** [comment]
I did some RnD on this issue and most of the solutions recommend downgrading node to 16.  However  there are a few others solutions.
- `export NODE_OPTIONS=--openssl-legacy-provider`. Setting Node to use legacy open ssl provider did the job for me.
- We can also change the hashing algorithm of webpack to sha25 but that seemed to cause further problems
- There is also another algorithm `xxhash64` but it is only available on webpack  5.54+

Links for reference 
- https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
- https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported

**Comment by pt2302** [comment]
@Wassaf-Shahzad Yes, that's what I saw as well. I think that the most likely way to resolve this issue and ensure compatibility with future Node versions would be to upgrade webpack.

**Comment by Wassaf-Shahzad** [comment]
> @Wassaf-Shahzad Yes, that's what I saw as well. I think that the most likely way to resolve this issue and ensure compatibility with future Node versions would be to upgrade webpack.

Ok thanks, I will have a PR ready late today or early tomorrow.
