### ISSUE TITLE
Styling tweaks for video player and video player page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#802]
![image](https://user-images.githubusercontent.com/430126/180290797-3cf03dab-ad14-433f-9ec0-858ebcd0c985.png)

from https://ocw.mit.edu/courses/18-02-multivariable-calculus-fall-2007/resources/lecture-3-matrices/

#### Designs and Mockups

https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/461529499/preview?scrollOffset=1982

#### Acceptance Criteria:

- [ ] The video timeline should extend the full width of the video player. Compare a youtube player to ours. 
- [ ] "Related Resource" UI should have same styling as Transcript UI: same controls, same colors

**Comment by pdpinch** [comment]
If it's easier, these changes could be made to course-v2

**Comment by MAbdurrehman12** [comment]
Closed by https://github.com/mitodl/ocw-hugo-themes/pull/803
