### ISSUE TITLE
course v2 learning resource types icons

### ISSUE THREAD

**Issue by MAbdurrehman12** [mitodl/ocw-hugo-themes#813]
### Steps to Reproduce

- Either:
    - Build any course on new theme locally (How to do it? Check the description of this [PR](https://github.com/mitodl/ocw-hugo-themes/pull/784#issue-1291571736))
    - View this [course deployed on netlify](https://ocw-hugo-themes-course-pr-809--ocw-next.netlify.app/)
- Go to the course homepage
- View `learning resource types` icons

### Expected Behavior

- `Learning resource types` icons should be the same as what we have in the [design](https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/467361595/preview).

### Actual Behavior

- Old icons are being used. 

### Screenshot or Screencast

(Ignore the other issues in the screenshot. will have separate tickets for them)

![Nuts-and-Bolts-of-Business-Plans-Sloan-School-of-Management-MIT-OpenCourseWare](https://user-images.githubusercontent.com/93309234/183045799-62f470a6-d3dc-469f-8aac-93f4ea438dae.png)

**Comment by MAbdurrehman12** [comment]
@pdpinch In [invisionapp](https://projects.invisionapp.com/d/main?origin=v7#/projects/prototypes/21537330/assets?folderID=2310059062), we have only 4 learning resource types icons whereas currently, in old theme, we have around 12 material icons in total:
<img width="805" alt="image" src="https://user-images.githubusercontent.com/93309234/183888505-b872e0f1-b2ff-4bab-93fd-036b0c4b03ea.png">
however, the [total options](https://github.com/mitodl/ocw-hugo-projects/blob/32d4d8920f33e25cc143a2bd401fd407aaceb4c3/ocw-course/ocw-studio.yaml#L152) of learning resource types are more than that but I assume we are using 1 icon for multiple types that are similar. 

So I think we'll need to have the replacement/alternate of all these 12 icons so I can replace them all.
ps: I also think that svgs will be better but we can get the designer's thoughts on this.

**Comment by pdpinch** [comment]
I started a google sheet so we can review the mapping of resource types to icons: https://docs.google.com/spreadsheets/d/1rlyOUMHHEJ9hOBwZ8QwZo8SQTA-eC0eLGqmaFIt3V78/edit#gid=0

Can you help me fill it in? Is there someplace in the code where I can see the current mapping?

**Comment by MAbdurrehman12** [comment]
> I started a google sheet so we can review the mapping of resource types to icons

Thanks

> Can you help me fill it in

Sure

> Is there someplace in the code where I can see the current mapping?

Yeah, the mapping is in [learning_resource_type.html](https://github.com/mitodl/ocw-hugo-themes/blob/dc57e81d9ee4b2dcf54e1543c66ffb53ca32ccaf/course-v2/layouts/partials/learning_resource_type.html#L8) but not sure if it's easy to understand.

Strings between Hugo's if else are the material icons:
e.g: 
```
{{- if eq $context "Course Introduction" -}}
      groups
{{- else if in $context "Audio" -}}
      equalizer
....
```
`Course Introduction` type has the icon `groups`.
`Audio` type has the icon `equalizer` and so on

**Comment by MAbdurrehman12** [comment]
Got closed mistakenly, so reopening this

**Comment by pdpinch** [comment]
@MAbdurrehman12 we completed the course-v2 redesign somehow without resolving this issue. Can you update this with what we currently have and what remains to be done (if anything) ?

**Comment by MAbdurrehman12** [comment]
@pdpinch We had new icons for learning resource types that can be seen in the [design](https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/467361595/preview), however, we need all icons for all types which are pending at the moment.
Type to icon mapping can be seen [here](https://docs.google.com/spreadsheets/d/1rlyOUMHHEJ9hOBwZ8QwZo8SQTA-eC0eLGqmaFIt3V78/edit#gid=0)

**Comment by pdpinch** [comment]
@MAbdurrehman12 what's the state of this currently? If we don't have an icon for a course's learning resource type, what do we display?

**Comment by MAbdurrehman12** [comment]
>what's the state of this currently?

@pdpinch The state of this ticket is the same as described in this [comment](https://github.com/mitodl/ocw-hugo-themes/issues/813#issuecomment-1210547562)

> If we don't have an icon for a course's learning resource type, what do we display?

I think all learning resource types are being displayed from this [file](https://github.com/mitodl/ocw-hugo-themes/blob/dc57e81d9ee4b2dcf54e1543c66ffb53ca32ccaf/course-v2/layouts/partials/learning_resource_type.html).
We just need to replace the old icons with the new ones shown in this [design](https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/467361595/preview)

**Comment by pdpinch** [comment]
We've been living with this as is for some time now. If we want to update these icons, we will align it with Learn designs.
