### ISSUE TITLE
Make ocw bundles smaller

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-hugo-themes#856]
In #855, I added a webpack-bundle-analyzer so we can better understand what is in our bundled code. Here's the output:

<img width="1810" alt="Screen Shot 2022-09-20 at 4 27 32 PM" src="https://user-images.githubusercontent.com/9010790/191359839-4719e749-014e-4166-811a-f22c4d0df1a8.png">

Based on that analysis, here are a few things I think we could do to improve our page-load performance:

#### Easy stuff
- Load jquery as a separate chunk. My understanding is that this would have two benefits:
    - users would only download jquery once; jquery is in all 3 chunks: main, course, and www . So when a user visits a course, they download it twice (main+course) and also twice when they visit www (course+www). That's 4 downloads of jquery, but we only need one. 
    - Right now when we cut a new theme release, users have to download jquery again. But if it's a separate bundle, its hash would not change when we cut a release (unless we bump its version) so jquery would be loaded from user's cache.
- bundle video.js separately. _Won't decrease our size, but similar caching benefit to above when we cut a new release of hugo-themes._
-  Stop using `ramda` and consistently use `lodash` instead. The two libraries are very, very similar. There's no need for us to be using both. _ramda is about 7% of the g-zipped www bundle._
- Do not include all of lodash; or perhaps get rid of it all together. We are including all of lodash right now because course-search-utils does. Course-search-utils should either not use lodash at all, or import just the pieces it needs (like `import { isEqual } from "lodash/isEqual"`). 

    _Lodash is about 14% of our overall ocw-www bundle._

### Other stuff:
- We could probably use [preact](https://www.npmjs.com/package/preact) if we want... I've never used it personally, but my understanding is that it is a drop-in replacement from react in most simple cases. And our OCW usage is pretty simple.
- video.js is big. Dunno if there's anything we can do about that.
- nanogallery is big. Dunno if there's anything we could do about that.

**Comment by Ferdi** [comment]
This is great !

* Are we using react only in search pages ?   Does it load only when you are in the search context ?
* re:nanogallery: Can we find the most minimal image gallery out there.  The image galleries are minimally used in ocw

**Comment by ChristopherChudzicki** [comment]
> Are we using react only in search pages ? Does it load only when you are in the search context ?
Right now:

Looks like we use react for search page, course lists, resource collections. Right now:

- **main + course**: is loaded by all course pages
- **main + www** is loaded by all all www pages (homepage, search, stories)

React is in the www chunk, so courses don't load it, but homepage, search, etc, do.

> re:nanogallery: Can we find the most minimal image gallery out there. The image galleries are minimally used in ocw

[photoswipe](https://www.npmjs.com/package/photoswipe) might be a reasonable candidate. gzipped, it's about 30% the size of nanogallery.

Something that @pdpinch has mentioned is working on including this libraries (videojs, image gallery, whatever) only on the content pages that use them.

**Comment by ChristopherChudzicki** [comment]
Closing this. #1059 did a lot of it. Remaining stuff is tracked by https://github.com/mitodl/ocw-hugo-themes/issues/618
