### ISSUE TITLE
No Learning Resource Types section should be displayed if there are none

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-hugo-themes#86]
### Steps to Reproduce

You can see this on https://ocwnext-rc.odl.mit.edu/courses/11-405-just-money-banking-as-if-society-mattered-spring-2021/. If there are no features we should omit the section

![Screenshot_20210603-150233](https://user-images.githubusercontent.com/863262/120698240-c67cf980-c47c-11eb-9a55-e4321861ef35.png)

**Comment by MAbdurrehman12** [comment]
@annagav Are you working on this or can I do it?

**Comment by annagav** [comment]
@MAbdurrehman12 yes, you can take it. Sorry I forgot to unassign myself

**Comment by MAbdurrehman12** [comment]
@pdpinch This ticket was opened by George, but I'm unable to find **course features** and unable to reproduce the issue. However, a similar issue is there for **learning resource types**, maybe course features has been renamed but I'm not sure.
Anyways, I have created a PR for learning resource types.

Please let me know if you have any thoughts on this.

**Comment by pdpinch** [comment]
Thank you @MAbdurrehman12, I forgot the page section was changed to "Learning Resource Types" some time ago.
