### ISSUE TITLE
course main content takes up full screen width from 1620px to 1800px

### ISSUE THREAD

**Issue by MAbdurrehman12** [mitodl/ocw-hugo-themes#873]
### Steps to Reproduce

- Go to either CHP or any interior page.
- Set the screen width anywhere between 1620px to 1800px
- Now note that the content takes full-screen width instead of being wrapped up in a container/no max-width seems to be set whereas the footer seems to be wrapped up in a max-width container, hence now course content is also not aligned with footer

### Expected Behavior

- I think course content should be wrapped up in a max-width container so it does not fully expand like this. 

### Actual Behavior

- content takes full-screen width instead of being wrapped up in a container/no max-width seems to be set.

### Screenshot or Screencast

https://user-images.githubusercontent.com/93309234/193036743-5ad55aa0-0ef1-4f90-903a-3a43fdde110b.mov

**Comment by pdpinch** [comment]
> I think course content should be wrapped up in a max-width container so it does not fully expand like this.

Yes please
