### ISSUE TITLE
www landing page breaks when no new courses or new courses API fails 

### ISSUE THREAD

**Issue by MAbdurrehman12** [mitodl/ocw-hugo-themes#880]
### Steps to Reproduce

- On www landing page, make the new courses API fail (they are currently failing on my local setup because I don't have any new course in my content, though the API shouldn't be called on this in-case of no courses but I'm not very sure since I haven't looked into it yet) 
- Set the screen size anywhere between `992px` - `1199px`
- Now note that the landing page has broken quite badly.
- Comment the code line `{{ partial "new_course_cards.html" $childPages }}` in `home.html` and now see that everything is fine.

### Expected Behavior

- If there are no new courses, there shouldn't be any fetch/API calls.
- Even if there are no new courses or even the API is failing, the layout should not break and an appropriate error msg should be shown.

### Actual Behavior

- Sections below `Discover collections` and above `footer` are very badly broken.

### Screenshot or Screencast

See this [video](https://drive.google.com/file/d/1n9iarW4quUT556r32HzHyH3Uk7pnW4nE/view?usp=sharing)
(Video was a bit big to attach here so it has been uploaded on the drive) 

<img width="930" alt="image" src="https://user-images.githubusercontent.com/93309234/193273080-4499c894-6250-45fb-8332-d0e67098225b.png">

**Comment by pdpinch** [comment]
This should never happen in a deployed environment
