### ISSUE TITLE
Images missing from published courses

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#882]
### Steps to Reproduce

1. This page has an image in studio: https://ocw-studio.odl.mit.edu/sites/1-74-land-water-food-and-climate-fall-2020/type/page/edit/93c1284a-2f23-874c-977a-debf44537cf1/?q=teaching
2. The markdown has a resource shortcode: https://github.mit.edu/mitocwcontent/1.74-fall-2020/blob/main/content/pages/instructor-insights/teaching-the-uncertainty.md
3. publish the course to https://draft.ocw.mit.edu/courses/1-74-land-water-food-and-climate-fall-2020/pages/instructor-insights/teaching-the-uncertainty/

### Expected Behavior

- There should be embedded images

### Actual Behavior

- There is no embedded image on the published version

**Comment by ChristopherChudzicki** [comment]
Closed by #883
