### ISSUE TITLE
do not include bootstrap twice

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-hugo-themes#892]
### Steps to Reproduce

1. Visit any ocw course, like https://ocw.mit.edu/courses/11-382-water-diplomacy-spring-2021/ for example
2. In network tab, filter for css... you should see both "main" and "course" files:
    <img width="696" alt="Screen Shot 2022-10-05 at 10 04 17 AM" src="https://user-images.githubusercontent.com/9010790/194080219-695a05f5-5f34-40a5-81fc-7387ebd8e5ce.png">
3. Open "main" and search for "Bootstrap".
4. Open "course" and search for "Bootstrap".

### Expected Behavior
Only one chunk has bootstrap

### Actual Behavior
Both chunks have bootstrap

### Related Issues

#856

**Comment by pdpinch** [comment]
Is this still an issue?

**Comment by ChristopherChudzicki** [comment]
No, this was resolved by #1059

A separate issue is that we are including all of bootstrap when we probably don't need all of bootstrap. But at least we are not including it all twice.
