### ISSUE TITLE
inconsistent styling in the video player 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#893]
### Steps to Reproduce

take a look at https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-1-the-geometry-of-linear-equations/

### Expected Behavior

The related resources button should look and behave like the transcript button. 

### Actual Behavior

They aren't the same. 

### Screenshot or Screencast

<img width="612" alt="image" src="https://user-images.githubusercontent.com/430126/194115264-20ca1a41-dc25-4eb2-a491-19292df6d819.png">

**Comment by MAbdurrehman12** [comment]
closes by https://github.com/mitodl/ocw-hugo-themes/pull/902
