### ISSUE TITLE
On course section pages H3 is bigger than H2

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#90]
I think we had a similar problem with Instructor Insights pages, which was fixed in https://github.com/mitodl/ocw-hugo-themes/pull/64.

### Steps to Reproduce

See https://ocwnext.odl.mit.edu/courses/6-00sc-introduction-to-computer-science-and-programming-spring-2011/sections/unit-1/lecture-2-core-elements-of-a-program/

### Expected Behavior

The H2 should be larger than the H3. I think the colors should be reversed too, so the H2 is read and the H3 is black. 

### Actual Behavior

H3 is larger than H2.

### Screenshot or Screencast

from https://ocwnext.odl.mit.edu/courses/6-00sc-introduction-to-computer-science-and-programming-spring-2011/sections/unit-1/lecture-2-core-elements-of-a-program/

<img width="691" alt="image" src="https://user-images.githubusercontent.com/430126/121067393-00aa0c00-c799-11eb-89de-d4b5ceb2dbae.png">

**Comment by MAbdurrehman12** [comment]
@pdpinch I'm unable to reproduce this issue, the [link](https://ocwnext.odl.mit.edu/courses/6-00sc-introduction-to-computer-science-and-programming-spring-2011/sections/unit-1/lecture-2-core-elements-of-a-program/) given in "Steps to reproduce" also seems to broken.
Any suggestion for me to reproduce it on my local?
