### ISSUE TITLE
Migrate away from github actions/cache@v1 (deprecation)

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-hugo-themes#922]
Github actions `actions/cache@v1` uses some stuff that is getting deprecated...https://github.com/mitodl/ocw-hugo-themes/actions/runs/3283928848/jobs/5409258444#step:5:8

> Run actions/cache@v1
> Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

According to the block post, that warning will turn into an error on June 1st, 2023. I'm sure we'll get lots of warnings...

**Comment by HussainTaj-arbisoft** [comment]
`ocw-hugo-themes` no longer uses `actions/cache`. I'll take this opportunity to update ocw-studio's workflows instead. https://github.com/mitodl/ocw-studio/blob/9212ad0f88bd4662f46fb42a2134fe67aa905963/.github/workflows/ci.yml#L54
