### ISSUE TITLE
only show course download if ZIP file exists

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-hugo-themes#937]
As a user of OCW, I'd like to only be presented with course download links that work

#### Designs and Mockups

https://projects.invisionapp.com/share/PA131XTPEK76#/screens/470225774_Page_-_Download_Options_-_V1-1
https://invis.io/UX132JLIWE43#/470179934_OCW_-_Course_Home_V2-1
https://invis.io/6N12T6YA43PW#/467901625_OCW_-_Course_Detail_-_Sidebar_Alt_-__v-1-4

#### Acceptance Criteria:

- [ ] If the ZIP file for a course has not been generated yet or otherwise doesn't exist, don't show the download link

**Comment by gumaerc** [comment]
I've tried a couple different methods of doing this today and haven't been happy with any of them:

 - Firstly, I tried using Hugo's `resources.GetRemote` with `"method" "head"` to make a `HEAD` request during the build at the URL to check for its existence. This method will make the HEAD request but the object it returns is a Hugo `Resource` object that only contains the response body, not the response headers. Logging the response, I actually strangely enough get a blank string when requesting an invalid URL testing against QA. When requesting a valid ZIP file, I get an error like `error calling resources.GetRemote: failed to read remote resource "https://live-qa.ocw.mit.edu/courses/2-57-nano-to-macro-transport-processes-spring-2012/2.57-spring-2012.zip": unexpected EOF`. All in all, this method seems unusable. As with most things in Hugo, I found a thread where Bjorn shines some light on this and says "we're not adding some low-level HTTP API to Hugo" here: https://github.com/gohugoio/hugo/issues/7699#issuecomment-698753361
 - Secondly, I tried making the `HEAD` request client side and checking for a 404. This method is pretty simple and does work, but presents two issues:
   - Since this is on the client side, even using raw native JS and making sure it loads quickly as possible in-line like we have done in the past for the mobile table styling, there is a quick "flicker" while the HTTP request is being made to determine if the file exists. I'm not sure that there's a way around this as the HTTP request is always going to take a bit of time.
   - CORS is not a problem right now since the ZIP files will be hosted in the same bucket alongside the rest of the content, however if we decide to move them in the future it could become a problem.

So yea, neither of these options are really that great. With the Hugo method we could maybe tweak the Fastly response so that something shows up in response to a HEAD request that can be usable there but I'm not certain. At this point, I'm thinking a better strategy would be something along the lines of this:

 - Add a property to the `Website` model along the lines of `publish_date` called `offline_publish_date`
 - Create an API endpoint where the offline mass build could update this value when a build runs
 - During the Hugo build, hit the `ocw-studio` API to check `offline_publish_date` on the site and show / hide based on that

**Comment by pdpinch** [comment]
Wow, that's disappointing about `resources.GetRemote`. No error handling, huh?

I'm sure there's some way to deal with the flickering, but I'd rather not add a bunch of runtime JavaScript for something that could be determined at run time. 

> Add a property to the Website model along the lines of publish_date called offline_publish_date

This makes sense to me, and I'm a little surprised we haven't already done it. How else would we be able to keep track of whether the offline version is built? 

> Create an API endpoint where the offline mass build could update this value when a build runs

Don't we already have a webhook endpoint like this for course builds? I don't know if it makes sense to extend it, or add a new endpoint. 

> During the Hugo build, hit the ocw-studio API to check offline_publish_date on the site and show / hide based on that

I don't like adding another HTTP dependency to builds. Why not just add the metadata to the course's front matter?

**Comment by Ferdi** [comment]
It says it returns `nil` if file does not exists https://gohugo.io/hugo-pipes/introduction/#get-resource-with-resourcesget-and-resourcesgetremote

**Comment by gumaerc** [comment]
@Ferdi You are right, I gave the Hugo method another shot and had some success. I was getting errors while fetching the `HEAD` for the zip file and found that I needed to make a couple changes to the Hugo config to allow it.

**Comment by gumaerc** [comment]
@Ferdi @pdpinch So, I put up the above two PR's which does address the issue but I still have concerns. I noted them in the `ocw-hugo-themes` PR, but in a nutshell `resources.GetRemote` does not really support making a `HEAD` request, which is really what we need to be doing here. Doing the default `GET` request will fetch the entire ZIP file during the Hugo build for every single course if it exists. This could severely impact the time it takes to rebuild the whole site, which is why I wanted to do a `HEAD` request instead to simply fetch the headers and check if the file exists. When you do this, if Hugo gets a 404 it properly returns `nil`. However, when finding any actual file this way Hugo throws an `unexpected EOF` error. This is because it got a 200, indicating that the file exists and then tried to read the body of the request, of which there is none because it's a `HEAD` request. Therefore, the only way for us to know if the ZIP actually exists is to look for the `unexpected EOF` error to be thrown. "Task failed successfully" if you will. I don't feel super great about this, but I really don't feel great about just having Hugo download the entire ZIP file during the build of every course. So, the way I see it, our options are to either go with the PR the way I have it, have Hugo download the entire ZIP file (I'd anticipate at least doubling the build time depending on network conditions) or ditch trying to check the file itself during the build at all and just go with the `ocw-studio` method I detailed above.

**Comment by gumaerc** [comment]
@Ferdi @pdpinch I'm re-opening this issue as I discovered some issues while testing https://github.com/mitodl/ocw-hugo-themes/pull/960 in RC this morning:

 - Hugo needs a fully qualified URL to run `resources.GetRemote` against, since it's making the request during the build. This is a simple oversight on my part and fixing it is as simple as prefixing the request with `STATIC_API_BASE_URL`.
 - The bigger issue is that since we allow OCW to customize `short_id`, it is not a predictable pattern anymore of `<department number>.<course number>-<term>-<year>`. Recently the OCW team has used a different scheme that looks like `RES.3-006_Sp21`.
