### ISSUE TITLE
add links to the course download page

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-hugo-themes#938]
As a user of OCW, I'd like to see a link to download course materials

#### Designs and Mockups

https://invis.io/UX132JLIWE43#/470179934_OCW_-_Course_Home_V2-1
https://invis.io/6N12T6YA43PW#/467901625_OCW_-_Course_Detail_-_Sidebar_Alt_-__v-1-4

#### Acceptance Criteria:

- [ ] The course home page has a link to the resources index as indicated in the design above in the first link
- [ ] In the course info sidebar on other pages, there is also a link to the resources index as indicated in the design in the second link above
- [x] The existing page at `/resources` is instead rendered at `/download`

**Comment by Ferdi** [comment]
I think we should rename /resources page to /download

**Comment by gumaerc** [comment]
@Ferdi What do we expect to see at the root of `/resources` vs `/download`?

**Comment by Ferdi** [comment]
I was hoping we can have `/download`  replaces `/resources`   but leave  `/resources/lecture-videos` etc. as is.   Is that possible ?

**Comment by gumaerc** [comment]
Yep, that's controlled by [this line](https://github.com/mitodl/ocw-hugo-projects/blob/9e5d311441b9c6b4d8af67fd951009e32ded61b1/ocw-course-v2/config.yaml#L48) in the Hugo config, so as long as we don't change that the "see all" pages will stay the same at `/resources`. I can certainly move the `/resources` page to `/download`, but my question is what do we expect to be at `/resources` in its place? Since we have content at `/resources`, the `single.html` template renders the individual resource pages and Hugo automatically tries to render an index page there. It ends up being blank because the only templates matching it are the base template, like this:

![chrome_2022-10-31_15-43-33](https://user-images.githubusercontent.com/12089658/199096587-e63c667a-61fd-472a-ac52-c33650f79851.png)

So, I'm wondering what we should expect here. A few options that come to mind:

 - 301 Redirect to `/download`
 - A separate template with the resource lists minus the download button
 - 404 / don't render a page
