### ISSUE TITLE
more use of "Show more" 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#955]
In https://github.com/mitodl/ocw-hugo-themes/pull/876 we replaced the line/arrow UI for truncating text on the CHP with a "show more"/"show less" UI. 

But we still have the old UI on some resource pages, like https://live-qa.ocw.mit.edu/courses/res-tll-008-social-and-ethical-responsibilities-of-computing-serc-fall-2021/resources/res-tll-008f21-sts047-1/

#### Screenshots

![image](https://user-images.githubusercontent.com/430126/199603581-730fd944-6876-40e1-b2de-aaa29ce6ad6f.png)

![image](https://user-images.githubusercontent.com/430126/199603688-636976a6-1cba-42c1-9090-aa66889f8991.png)

#### Acceptance Criteria:

- [ ] Use the same show more UI everywhere
- [ ] get rid of the lines and arrows

**Comment by Ferdi** [comment]
I would simply show the full title.

**Comment by MAbdurrehman12** [comment]
For reference/comparison: `show more/show less` looks something like this:

https://user-images.githubusercontent.com/93309234/199702631-547208c7-0eed-48eb-989a-2ca3735553cd.mov

**Comment by pdpinch** [comment]
What does the longest resource title look like, if we go with showing the full title? 

The longest resource title is #3 in this search result: https://live-qa.ocw.mit.edu/search/?q=%22Theory%20of%20Discounted%20Problems%22&type=resourcefile&u=compact

**Comment by MAbdurrehman12** [comment]
> What does the longest resource title look like, if we go with showing the full title?
> 
> The longest resource title is #3 in this search result: https://live-qa.ocw.mit.edu/search/?q=%22Theory%20of%20Discounted%20Problems%22&type=resourcefile&u=compact

<img width="1377" alt="image" src="https://user-images.githubusercontent.com/93309234/199920325-8d0682d0-4c05-4056-8903-33cb62067fc5.png">

not sure but I think such long titles are not very common, usually titles are of normal length. So as per @Ferdi's suggestion, I think it would be okay to simply show the full title
