### ISSUE TITLE
Reorder Resources by Number in Course Download Pages

### ISSUE THREAD

**Issue by pt2302** [mitodl/ocw-hugo-themes#958]
### Steps to Reproduce

In the course download pages, lecture videos are ordered lexicographically (1, 10, 11, 12, ..., 2, 20, 21, ...) rather than by number (1,2,3,4,...).

Some examples:

https://ocw.mit.edu/courses/9-40-introduction-to-neural-computation-spring-2018/download/
https://ocw.mit.edu/courses/21l-011-the-film-experience-fall-2013/download/

### Expected Behavior

The videos should be ordered by number.

### Actual Behavior

The videos are ordered lexicographically.

**Comment by pdpinch** [comment]
@ibrahimjaved12 since you have a PR for this, I'm reassigning it to you.
