### ISSUE TITLE
Remove old "course" theme.

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-hugo-themes#986]
We currently have two course themes, "course" and "course-v2". This causes some confusion, especially in regards to bug fixes.

Many of the bugs in "course-v2", e.g., #982, were inherited from "course". So when we fix the bug, do we fix it in both or just v2? And if we fix it in both, should reviewers test the change in both? Should we verify the commit on rc in both? (Probably not).  This is especially confusing for new contributors.

### Acceptance Criteria
- [ ] confirm that no courses on prod/rc are using the theme
- [ ] remove old "course" theme and associated CI actions
- [ ] remove old course config from ocw-hugo-projects

**Comment by ChristopherChudzicki** [comment]
@gumaerc Am I missing anything in the above to-do list?

@pdpinch @gumaerc are we actually ok removing the old theme? I think we should. It has caused confusion in some PRs. (e.g., #984 )

**Comment by gumaerc** [comment]
I think we are good to remove the original course theme at this point. We should preserve a copy of it somewhere in version control in case we ever need to refer to it in the future for historical reasons, but there shouldn't be anything actively using it anymore.
