### ISSUE TITLE
Update style of all headings/titles for desktop and mobile according to OCW Style Guide

### ISSUE THREAD

**Issue by MAbdurrehman12** [mitodl/ocw-hugo-themes#991]
### Issue description

Need to update the headings/titles CSS according to the updated [OCW style guide](https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/468374061/preview?scrollOffset=63.5)

### Issue old description

- Go to any course page and look at the title
- Note that the titles are too strong (bold) compared to the weight of other text.
- Ref: https://github.com/mitodl/ocw-hugo-themes/pull/961#issuecomment-1304633572 & https://github.com/mitodl/ocw-hugo-themes/pull/961#issuecomment-1320121794 

### Screenshot or Screencast

<img width="984" alt="image" src="https://user-images.githubusercontent.com/93309234/203018957-8899bb5e-e611-46e5-b53d-a3a95c5d7348.png">

<img width="317" alt="image" src="https://user-images.githubusercontent.com/93309234/203018851-6bab5281-79f3-402a-93c9-855e808b3eda.png">

**Comment by MAbdurrehman12** [comment]
Please have a look at some before/after pictures of reducing `font-weight` of headings and let me know what you think.

**Normal weight:**
<img width="345" alt="Screenshot 2022-11-21 at 4 38 08 PM" src="https://user-images.githubusercontent.com/93309234/203043595-d8a93833-e27c-4ab0-9d73-d1f8c449572c.png">
**Reduced weight:**
<img width="314" alt="Screenshot 2022-11-21 at 4 36 21 PM" src="https://user-images.githubusercontent.com/93309234/203043565-cdaa1162-a49e-4649-a0ba-782ea54e0a5b.png">

---------------------
**Normal weight:**
<img width="562" alt="Screenshot 2022-11-21 at 4 44 01 PM" src="https://user-images.githubusercontent.com/93309234/203043628-ce62a620-3237-483e-8ec1-4f20666b2b69.png">
**Reduced weight:**
<img width="566" alt="Screenshot 2022-11-21 at 4 44 14 PM" src="https://user-images.githubusercontent.com/93309234/203043644-9c675503-31f2-41c1-b90c-dae05501e3cf.png">

---------------------
**Normal weight:**
<img width="833" alt="Screenshot 2022-11-21 at 4 38 40 PM" src="https://user-images.githubusercontent.com/93309234/203043601-058a4f9a-5652-43bb-8fc4-efd6f78e932b.png">
**Reduced weight:**
<img width="828" alt="Screenshot 2022-11-21 at 4 39 18 PM" src="https://user-images.githubusercontent.com/93309234/203043611-d92defc3-9bc8-404d-bf7d-e6cbacc722b4.png">

---------------------
**Normal weight:**
<img width="347" alt="Screenshot 2022-11-21 at 4 40 56 PM" src="https://user-images.githubusercontent.com/93309234/203043618-e12f5492-e9e9-4e21-b9ec-57822b565de6.png">
**Reduced weight:**
<img width="421" alt="Screenshot 2022-11-21 at 4 40 47 PM" src="https://user-images.githubusercontent.com/93309234/203043615-b312d4b7-e1c5-43da-b379-d15dcddd76ee.png">

**Comment by Ferdi** [comment]
@MAbdurrehman12 thanks for looking into this.  I would say  it looks good but I suggest we ask a pro on this one.

**Comment by MAbdurrehman12** [comment]
> I would say it looks good but I suggest we ask a pro on this one.

Maybe we can get some feedback from Nicolae or if we have any other UI/UX designer?
